// This file is auto-generated by @hey-api/openapi-ts

import type { AcceptContractResponse, CreateChartResponse, CreateShipShipScanResponse, CreateShipSystemScanResponse, CreateShipWaypointScanResponse, CreateSurveyResponse, DeliverContractResponse, DockShipResponse, ExtractResourcesResponse, ExtractResourcesWithSurveyResponse, FulfillContractResponse, GetAgentResponse, GetAgentsResponse, GetContractResponse, GetContractsResponse, GetMarketResponse, GetMyAccountResponse, GetMyAgentEventsResponse, GetMyAgentResponse, GetMyShipResponse, GetMyShipsResponse, GetRepairShipResponse, GetScrapShipResponse, GetShipNavResponse, GetShipyardResponse, GetStatusResponse, GetSystemWaypointsResponse, GetWaypointResponse, InstallMountResponse, InstallShipModuleResponse, JumpShipResponse, NavigateShipResponse, NegotiateContractResponse, OrbitShipResponse, PatchShipNavResponse, PurchaseCargoResponse, PurchaseShipResponse, RefuelShipResponse, RegisterResponse, RemoveMountResponse, RemoveShipModuleResponse, RepairShipResponse, ScrapShipResponse, SellCargoResponse, ShipRefineResponse, SiphonResourcesResponse, WarpShipResponse } from './types.gen';

const publicAgentSchemaResponseTransformer = (data: any) => {
    data.credits = BigInt(data.credits.toString());
    return data;
};

export const getAgentsResponseTransformer = async (data: any): Promise<GetAgentsResponse> => {
    data.data = data.data.map((item: any) => publicAgentSchemaResponseTransformer(item));
    return data;
};

export const getAgentResponseTransformer = async (data: any): Promise<GetAgentResponse> => {
    data.data = publicAgentSchemaResponseTransformer(data.data);
    return data;
};

export const getStatusResponseTransformer = async (data: any): Promise<GetStatusResponse> => {
    data.leaderboards.mostCredits = data.leaderboards.mostCredits.map((item: any) => {
        item.credits = BigInt(item.credits.toString());
        return item;
    });
    return data;
};

const chartSchemaResponseTransformer = (data: any) => {
    data.submittedOn = new Date(data.submittedOn);
    return data;
};

const waypointSchemaResponseTransformer = (data: any) => {
    if (data.chart) {
        data.chart = chartSchemaResponseTransformer(data.chart);
    }
    return data;
};

export const getSystemWaypointsResponseTransformer = async (data: any): Promise<GetSystemWaypointsResponse> => {
    data.data = data.data.map((item: any) => waypointSchemaResponseTransformer(item));
    return data;
};

export const getWaypointResponseTransformer = async (data: any): Promise<GetWaypointResponse> => {
    data.data = waypointSchemaResponseTransformer(data.data);
    return data;
};

const marketTransactionSchemaResponseTransformer = (data: any) => {
    data.timestamp = new Date(data.timestamp);
    return data;
};

const marketSchemaResponseTransformer = (data: any) => {
    if (data.transactions) {
        data.transactions = data.transactions.map((item: any) => marketTransactionSchemaResponseTransformer(item));
    }
    return data;
};

export const getMarketResponseTransformer = async (data: any): Promise<GetMarketResponse> => {
    data.data = marketSchemaResponseTransformer(data.data);
    return data;
};

const shipyardTransactionSchemaResponseTransformer = (data: any) => {
    data.timestamp = new Date(data.timestamp);
    return data;
};

const shipyardSchemaResponseTransformer = (data: any) => {
    if (data.transactions) {
        data.transactions = data.transactions.map((item: any) => shipyardTransactionSchemaResponseTransformer(item));
    }
    return data;
};

export const getShipyardResponseTransformer = async (data: any): Promise<GetShipyardResponse> => {
    data.data = shipyardSchemaResponseTransformer(data.data);
    return data;
};

const contractTermsSchemaResponseTransformer = (data: any) => {
    data.deadline = new Date(data.deadline);
    return data;
};

const contractSchemaResponseTransformer = (data: any) => {
    data.terms = contractTermsSchemaResponseTransformer(data.terms);
    data.expiration = new Date(data.expiration);
    if (data.deadlineToAccept) {
        data.deadlineToAccept = new Date(data.deadlineToAccept);
    }
    return data;
};

export const getContractsResponseTransformer = async (data: any): Promise<GetContractsResponse> => {
    data.data = data.data.map((item: any) => contractSchemaResponseTransformer(item));
    return data;
};

export const getContractResponseTransformer = async (data: any): Promise<GetContractResponse> => {
    data.data = contractSchemaResponseTransformer(data.data);
    return data;
};

const agentSchemaResponseTransformer = (data: any) => {
    data.credits = BigInt(data.credits.toString());
    return data;
};

export const acceptContractResponseTransformer = async (data: any): Promise<AcceptContractResponse> => {
    data.data.contract = contractSchemaResponseTransformer(data.data.contract);
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    return data;
};

export const fulfillContractResponseTransformer = async (data: any): Promise<FulfillContractResponse> => {
    data.data.contract = contractSchemaResponseTransformer(data.data.contract);
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    return data;
};

export const deliverContractResponseTransformer = async (data: any): Promise<DeliverContractResponse> => {
    data.data.contract = contractSchemaResponseTransformer(data.data.contract);
    return data;
};

export const getMyAgentResponseTransformer = async (data: any): Promise<GetMyAgentResponse> => {
    data.data = agentSchemaResponseTransformer(data.data);
    return data;
};

const agentEventSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const getMyAgentEventsResponseTransformer = async (data: any): Promise<GetMyAgentEventsResponse> => {
    data.data = data.data.map((item: any) => agentEventSchemaResponseTransformer(item));
    return data;
};

const shipNavRouteSchemaResponseTransformer = (data: any) => {
    data.departureTime = new Date(data.departureTime);
    data.arrival = new Date(data.arrival);
    return data;
};

const shipNavSchemaResponseTransformer = (data: any) => {
    data.route = shipNavRouteSchemaResponseTransformer(data.route);
    return data;
};

const shipFuelSchemaResponseTransformer = (data: any) => {
    if (data.consumed) {
        data.consumed.timestamp = new Date(data.consumed.timestamp);
    }
    return data;
};

const cooldownSchemaResponseTransformer = (data: any) => {
    if (data.expiration) {
        data.expiration = new Date(data.expiration);
    }
    return data;
};

const shipSchemaResponseTransformer = (data: any) => {
    data.nav = shipNavSchemaResponseTransformer(data.nav);
    data.fuel = shipFuelSchemaResponseTransformer(data.fuel);
    data.cooldown = cooldownSchemaResponseTransformer(data.cooldown);
    return data;
};

export const getMyShipsResponseTransformer = async (data: any): Promise<GetMyShipsResponse> => {
    data.data = data.data.map((item: any) => shipSchemaResponseTransformer(item));
    return data;
};

export const purchaseShipResponseTransformer = async (data: any): Promise<PurchaseShipResponse> => {
    data.data.ship = shipSchemaResponseTransformer(data.data.ship);
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    data.data.transaction = shipyardTransactionSchemaResponseTransformer(data.data.transaction);
    return data;
};

export const getMyAccountResponseTransformer = async (data: any): Promise<GetMyAccountResponse> => {
    data.data.account.createdAt = new Date(data.data.account.createdAt);
    return data;
};

export const getMyShipResponseTransformer = async (data: any): Promise<GetMyShipResponse> => {
    data.data = shipSchemaResponseTransformer(data.data);
    return data;
};

const chartTransactionSchemaResponseTransformer = (data: any) => {
    data.timestamp = new Date(data.timestamp);
    return data;
};

export const createChartResponseTransformer = async (data: any): Promise<CreateChartResponse> => {
    data.data.chart = chartSchemaResponseTransformer(data.data.chart);
    data.data.waypoint = waypointSchemaResponseTransformer(data.data.waypoint);
    data.data.transaction = chartTransactionSchemaResponseTransformer(data.data.transaction);
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    return data;
};

export const negotiateContractResponseTransformer = async (data: any): Promise<NegotiateContractResponse> => {
    data.data.contract = contractSchemaResponseTransformer(data.data.contract);
    return data;
};

export const dockShipResponseTransformer = async (data: any): Promise<DockShipResponse> => {
    data.data.nav = shipNavSchemaResponseTransformer(data.data.nav);
    return data;
};

export const extractResourcesResponseTransformer = async (data: any): Promise<ExtractResourcesResponse> => {
    data.data.cooldown = cooldownSchemaResponseTransformer(data.data.cooldown);
    return data;
};

export const extractResourcesWithSurveyResponseTransformer = async (data: any): Promise<ExtractResourcesWithSurveyResponse> => {
    data.data.cooldown = cooldownSchemaResponseTransformer(data.data.cooldown);
    return data;
};

export const jumpShipResponseTransformer = async (data: any): Promise<JumpShipResponse> => {
    data.data.nav = shipNavSchemaResponseTransformer(data.data.nav);
    data.data.cooldown = cooldownSchemaResponseTransformer(data.data.cooldown);
    data.data.transaction = marketTransactionSchemaResponseTransformer(data.data.transaction);
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    return data;
};

export const createShipSystemScanResponseTransformer = async (data: any): Promise<CreateShipSystemScanResponse> => {
    data.data.cooldown = cooldownSchemaResponseTransformer(data.data.cooldown);
    return data;
};

const scannedWaypointSchemaResponseTransformer = (data: any) => {
    if (data.chart) {
        data.chart = chartSchemaResponseTransformer(data.chart);
    }
    return data;
};

export const createShipWaypointScanResponseTransformer = async (data: any): Promise<CreateShipWaypointScanResponse> => {
    data.data.cooldown = cooldownSchemaResponseTransformer(data.data.cooldown);
    data.data.waypoints = data.data.waypoints.map((item: any) => scannedWaypointSchemaResponseTransformer(item));
    return data;
};

const scannedShipSchemaResponseTransformer = (data: any) => {
    data.nav = shipNavSchemaResponseTransformer(data.nav);
    return data;
};

export const createShipShipScanResponseTransformer = async (data: any): Promise<CreateShipShipScanResponse> => {
    data.data.cooldown = cooldownSchemaResponseTransformer(data.data.cooldown);
    data.data.ships = data.data.ships.map((item: any) => scannedShipSchemaResponseTransformer(item));
    return data;
};

const scrapTransactionSchemaResponseTransformer = (data: any) => {
    data.timestamp = new Date(data.timestamp);
    return data;
};

export const getScrapShipResponseTransformer = async (data: any): Promise<GetScrapShipResponse> => {
    data.data.transaction = scrapTransactionSchemaResponseTransformer(data.data.transaction);
    return data;
};

export const scrapShipResponseTransformer = async (data: any): Promise<ScrapShipResponse> => {
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    data.data.transaction = scrapTransactionSchemaResponseTransformer(data.data.transaction);
    return data;
};

export const navigateShipResponseTransformer = async (data: any): Promise<NavigateShipResponse> => {
    data.data.nav = shipNavSchemaResponseTransformer(data.data.nav);
    data.data.fuel = shipFuelSchemaResponseTransformer(data.data.fuel);
    return data;
};

export const warpShipResponseTransformer = async (data: any): Promise<WarpShipResponse> => {
    data.data.nav = shipNavSchemaResponseTransformer(data.data.nav);
    data.data.fuel = shipFuelSchemaResponseTransformer(data.data.fuel);
    return data;
};

export const orbitShipResponseTransformer = async (data: any): Promise<OrbitShipResponse> => {
    data.data.nav = shipNavSchemaResponseTransformer(data.data.nav);
    return data;
};

export const purchaseCargoResponseTransformer = async (data: any): Promise<PurchaseCargoResponse> => {
    data.data.transaction = marketTransactionSchemaResponseTransformer(data.data.transaction);
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    return data;
};

export const shipRefineResponseTransformer = async (data: any): Promise<ShipRefineResponse> => {
    data.data.cooldown = cooldownSchemaResponseTransformer(data.data.cooldown);
    return data;
};

export const refuelShipResponseTransformer = async (data: any): Promise<RefuelShipResponse> => {
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    data.data.fuel = shipFuelSchemaResponseTransformer(data.data.fuel);
    data.data.transaction = marketTransactionSchemaResponseTransformer(data.data.transaction);
    return data;
};

const repairTransactionSchemaResponseTransformer = (data: any) => {
    data.timestamp = new Date(data.timestamp);
    return data;
};

export const getRepairShipResponseTransformer = async (data: any): Promise<GetRepairShipResponse> => {
    data.data.transaction = repairTransactionSchemaResponseTransformer(data.data.transaction);
    return data;
};

export const repairShipResponseTransformer = async (data: any): Promise<RepairShipResponse> => {
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    data.data.ship = shipSchemaResponseTransformer(data.data.ship);
    data.data.transaction = repairTransactionSchemaResponseTransformer(data.data.transaction);
    return data;
};

export const sellCargoResponseTransformer = async (data: any): Promise<SellCargoResponse> => {
    data.data.transaction = marketTransactionSchemaResponseTransformer(data.data.transaction);
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    return data;
};

export const siphonResourcesResponseTransformer = async (data: any): Promise<SiphonResourcesResponse> => {
    data.data.cooldown = cooldownSchemaResponseTransformer(data.data.cooldown);
    return data;
};

const surveySchemaResponseTransformer = (data: any) => {
    data.expiration = new Date(data.expiration);
    return data;
};

export const createSurveyResponseTransformer = async (data: any): Promise<CreateSurveyResponse> => {
    data.data.cooldown = cooldownSchemaResponseTransformer(data.data.cooldown);
    data.data.surveys = data.data.surveys.map((item: any) => surveySchemaResponseTransformer(item));
    return data;
};

const shipModificationTransactionSchemaResponseTransformer = (data: any) => {
    data.timestamp = new Date(data.timestamp);
    return data;
};

export const installShipModuleResponseTransformer = async (data: any): Promise<InstallShipModuleResponse> => {
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    data.data.transaction = shipModificationTransactionSchemaResponseTransformer(data.data.transaction);
    return data;
};

export const removeShipModuleResponseTransformer = async (data: any): Promise<RemoveShipModuleResponse> => {
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    data.data.transaction = shipModificationTransactionSchemaResponseTransformer(data.data.transaction);
    return data;
};

export const installMountResponseTransformer = async (data: any): Promise<InstallMountResponse> => {
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    data.data.transaction = shipModificationTransactionSchemaResponseTransformer(data.data.transaction);
    return data;
};

export const removeMountResponseTransformer = async (data: any): Promise<RemoveMountResponse> => {
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    data.data.transaction = shipModificationTransactionSchemaResponseTransformer(data.data.transaction);
    return data;
};

export const getShipNavResponseTransformer = async (data: any): Promise<GetShipNavResponse> => {
    data.data = shipNavSchemaResponseTransformer(data.data);
    return data;
};

export const patchShipNavResponseTransformer = async (data: any): Promise<PatchShipNavResponse> => {
    data.data.nav = shipNavSchemaResponseTransformer(data.data.nav);
    data.data.fuel = shipFuelSchemaResponseTransformer(data.data.fuel);
    return data;
};

export const registerResponseTransformer = async (data: any): Promise<RegisterResponse> => {
    data.data.agent = agentSchemaResponseTransformer(data.data.agent);
    data.data.contract = contractSchemaResponseTransformer(data.data.contract);
    data.data.ships = data.data.ships.map((item: any) => shipSchemaResponseTransformer(item));
    return data;
};
