// This file is auto-generated by @hey-api/openapi-ts

export const FactionSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/FactionSymbol'
        },
        name: {
            type: 'string',
            minLength: 1,
            description: 'Name of the faction.'
        },
        description: {
            type: 'string',
            minLength: 1,
            description: 'Description of the faction.'
        },
        headquarters: {
            type: 'string',
            minLength: 1,
            description: 'The waypoint in which the faction\'s HQ is located in.'
        },
        traits: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/FactionTrait'
            },
            description: 'List of traits that define this faction.'
        },
        isRecruiting: {
            type: 'boolean',
            description: 'Whether or not the faction is currently recruiting new agents.'
        }
    },
    required: [
        'symbol',
        'name',
        'description',
        'traits',
        'isRecruiting'
    ],
    description: 'Faction details.'
} as const;

export const FactionSymbolSchema = {
    type: 'string',
    enum: [
        'COSMIC',
        'VOID',
        'GALACTIC',
        'QUANTUM',
        'DOMINION',
        'ASTRO',
        'CORSAIRS',
        'OBSIDIAN',
        'AEGIS',
        'UNITED',
        'SOLITARY',
        'COBALT',
        'OMEGA',
        'ECHO',
        'LORDS',
        'CULT',
        'ANCIENTS',
        'SHADOW',
        'ETHEREAL'
    ],
    description: 'The symbol of the faction.'
} as const;

export const FactionTraitSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/FactionTraitSymbol'
        },
        name: {
            type: 'string',
            description: 'The name of the trait.'
        },
        description: {
            type: 'string',
            description: 'A description of the trait.'
        }
    },
    required: [
        'symbol',
        'name',
        'description'
    ]
} as const;

export const FactionTraitSymbolSchema = {
    type: 'string',
    enum: [
        'BUREAUCRATIC',
        'SECRETIVE',
        'CAPITALISTIC',
        'INDUSTRIOUS',
        'PEACEFUL',
        'DISTRUSTFUL',
        'WELCOMING',
        'SMUGGLERS',
        'SCAVENGERS',
        'REBELLIOUS',
        'EXILES',
        'PIRATES',
        'RAIDERS',
        'CLAN',
        'GUILD',
        'DOMINION',
        'FRINGE',
        'FORSAKEN',
        'ISOLATED',
        'LOCALIZED',
        'ESTABLISHED',
        'NOTABLE',
        'DOMINANT',
        'INESCAPABLE',
        'INNOVATIVE',
        'BOLD',
        'VISIONARY',
        'CURIOUS',
        'DARING',
        'EXPLORATORY',
        'RESOURCEFUL',
        'FLEXIBLE',
        'COOPERATIVE',
        'UNITED',
        'STRATEGIC',
        'INTELLIGENT',
        'RESEARCH_FOCUSED',
        'COLLABORATIVE',
        'PROGRESSIVE',
        'MILITARISTIC',
        'TECHNOLOGICALLY_ADVANCED',
        'AGGRESSIVE',
        'IMPERIALISTIC',
        'TREASURE_HUNTERS',
        'DEXTEROUS',
        'UNPREDICTABLE',
        'BRUTAL',
        'FLEETING',
        'ADAPTABLE',
        'SELF_SUFFICIENT',
        'DEFENSIVE',
        'PROUD',
        'DIVERSE',
        'INDEPENDENT',
        'SELF_INTERESTED',
        'FRAGMENTED',
        'COMMERCIAL',
        'FREE_MARKETS',
        'ENTREPRENEURIAL'
    ],
    description: 'The unique identifier of the trait.'
} as const;

export const MetaSchema = {
    type: 'object',
    properties: {
        total: {
            type: 'integer',
            minimum: 0,
            description: 'Shows the total amount of items of this kind that exist.'
        },
        page: {
            type: 'integer',
            minimum: 1,
            default: 1,
            description: 'A page denotes an amount of items, offset from the first item. Each page holds an amount of items equal to the `limit`.'
        },
        limit: {
            type: 'integer',
            minimum: 1,
            maximum: 20,
            default: 10,
            description: 'The amount of items in each page. Limits how many items can be fetched at once.'
        }
    },
    required: [
        'total',
        'page',
        'limit'
    ],
    description: 'Meta details for pagination.',
    'x-examples': {
        'example-1': {
            limit: 20,
            page: 1,
            total: 6
        }
    }
} as const;

export const PublicAgentSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            description: 'Symbol of the agent.',
            maxLength: 14,
            minLength: 3
        },
        headquarters: {
            type: 'string',
            description: 'The headquarters of the agent.',
            minLength: 1
        },
        credits: {
            type: 'integer',
            description: 'The number of credits the agent has available. Credits can be negative if funds have been overdrawn.',
            format: 'int64'
        },
        startingFaction: {
            type: 'string',
            description: 'The faction the agent started with.',
            minLength: 1
        },
        shipCount: {
            type: 'integer',
            description: 'How many ships are owned by the agent.'
        }
    },
    required: [
        'symbol',
        'headquarters',
        'credits',
        'startingFaction',
        'shipCount'
    ],
    description: 'Public agent details.'
} as const;

export const SystemSchema = {
    type: 'object',
    properties: {
        constellation: {
            type: 'string',
            description: 'The constellation that the system is part of.'
        },
        symbol: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the system.'
        },
        sectorSymbol: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the sector.'
        },
        type: {
            $ref: '#/components/schemas/SystemType'
        },
        x: {
            type: 'integer',
            description: 'Relative position of the system in the sector in the x axis.'
        },
        y: {
            type: 'integer',
            description: 'Relative position of the system in the sector in the y axis.'
        },
        waypoints: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/SystemWaypoint'
            },
            description: 'Waypoints in this system.'
        },
        factions: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/SystemFaction'
            },
            description: 'Factions that control this system.'
        },
        name: {
            type: 'string',
            description: 'The name of the system.'
        }
    },
    required: [
        'symbol',
        'sectorSymbol',
        'type',
        'x',
        'y',
        'waypoints',
        'factions'
    ],
    description: 'System details.'
} as const;

export const SystemTypeSchema = {
    type: 'string',
    enum: [
        'NEUTRON_STAR',
        'RED_STAR',
        'ORANGE_STAR',
        'BLUE_STAR',
        'YOUNG_STAR',
        'WHITE_DWARF',
        'BLACK_HOLE',
        'HYPERGIANT',
        'NEBULA',
        'UNSTABLE'
    ],
    description: 'The type of system.'
} as const;

export const SystemWaypointSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        type: {
            $ref: '#/components/schemas/WaypointType'
        },
        x: {
            type: 'integer',
            description: 'Relative position of the waypoint on the system\'s x axis. This is not an absolute position in the universe.'
        },
        y: {
            type: 'integer',
            description: 'Relative position of the waypoint on the system\'s y axis. This is not an absolute position in the universe.'
        },
        orbitals: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/WaypointOrbital'
            },
            description: 'Waypoints that orbit this waypoint.'
        },
        orbits: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.'
        }
    },
    required: [
        'symbol',
        'type',
        'x',
        'y',
        'orbitals'
    ],
    description: 'Waypoint details.'
} as const;

export const WaypointSymbolSchema = {
    type: 'string',
    description: 'The symbol of the waypoint.',
    minLength: 1,
    'x-faker': {
        fake: [
            'X1-{{random.alphaNumeric(4)}}-{{random.alphaNumeric(4)}}'
        ]
    }
} as const;

export const WaypointTypeSchema = {
    type: 'string',
    enum: [
        'PLANET',
        'GAS_GIANT',
        'MOON',
        'ORBITAL_STATION',
        'JUMP_GATE',
        'ASTEROID_FIELD',
        'ASTEROID',
        'ENGINEERED_ASTEROID',
        'ASTEROID_BASE',
        'NEBULA',
        'DEBRIS_FIELD',
        'GRAVITY_WELL',
        'ARTIFICIAL_GRAVITY_WELL',
        'FUEL_STATION'
    ],
    description: 'The type of waypoint.'
} as const;

export const WaypointOrbitalSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the orbiting waypoint.'
        }
    },
    required: [
        'symbol'
    ],
    description: 'An orbital is another waypoint that orbits a parent waypoint.'
} as const;

export const SystemFactionSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/FactionSymbol'
        }
    },
    required: [
        'symbol'
    ]
} as const;

export const WaypointSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        type: {
            $ref: '#/components/schemas/WaypointType'
        },
        systemSymbol: {
            $ref: '#/components/schemas/SystemSymbol'
        },
        x: {
            type: 'integer',
            description: 'Relative position of the waypoint on the system\'s x axis. This is not an absolute position in the universe.'
        },
        y: {
            type: 'integer',
            description: 'Relative position of the waypoint on the system\'s y axis. This is not an absolute position in the universe.'
        },
        orbitals: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/WaypointOrbital'
            },
            description: 'Waypoints that orbit this waypoint.'
        },
        orbits: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.'
        },
        faction: {
            $ref: '#/components/schemas/WaypointFaction'
        },
        traits: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/WaypointTrait'
            },
            description: 'The traits of the waypoint.'
        },
        modifiers: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/WaypointModifier'
            },
            description: 'The modifiers of the waypoint.'
        },
        chart: {
            $ref: '#/components/schemas/Chart'
        },
        isUnderConstruction: {
            type: 'boolean',
            description: 'True if the waypoint is under construction.'
        }
    },
    required: [
        'symbol',
        'type',
        'systemSymbol',
        'x',
        'y',
        'orbitals',
        'traits',
        'isUnderConstruction'
    ],
    description: 'A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.'
} as const;

export const SystemSymbolSchema = {
    type: 'string',
    minLength: 1,
    description: 'The symbol of the system.',
    'x-faker': {
        fake: [
            'X1-{{random.alphaNumeric(4)}}'
        ]
    }
} as const;

export const WaypointFactionSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/FactionSymbol'
        }
    },
    required: [
        'symbol'
    ],
    description: 'The faction that controls the waypoint.'
} as const;

export const WaypointTraitSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/WaypointTraitSymbol'
        },
        name: {
            type: 'string',
            description: 'The name of the trait.'
        },
        description: {
            type: 'string',
            description: 'A description of the trait.'
        }
    },
    required: [
        'symbol',
        'name',
        'description'
    ]
} as const;

export const WaypointTraitSymbolSchema = {
    type: 'string',
    enum: [
        'UNCHARTED',
        'UNDER_CONSTRUCTION',
        'MARKETPLACE',
        'SHIPYARD',
        'OUTPOST',
        'SCATTERED_SETTLEMENTS',
        'SPRAWLING_CITIES',
        'MEGA_STRUCTURES',
        'PIRATE_BASE',
        'OVERCROWDED',
        'HIGH_TECH',
        'CORRUPT',
        'BUREAUCRATIC',
        'TRADING_HUB',
        'INDUSTRIAL',
        'BLACK_MARKET',
        'RESEARCH_FACILITY',
        'MILITARY_BASE',
        'SURVEILLANCE_OUTPOST',
        'EXPLORATION_OUTPOST',
        'MINERAL_DEPOSITS',
        'COMMON_METAL_DEPOSITS',
        'PRECIOUS_METAL_DEPOSITS',
        'RARE_METAL_DEPOSITS',
        'METHANE_POOLS',
        'ICE_CRYSTALS',
        'EXPLOSIVE_GASES',
        'STRONG_MAGNETOSPHERE',
        'VIBRANT_AURORAS',
        'SALT_FLATS',
        'CANYONS',
        'PERPETUAL_DAYLIGHT',
        'PERPETUAL_OVERCAST',
        'DRY_SEABEDS',
        'MAGMA_SEAS',
        'SUPERVOLCANOES',
        'ASH_CLOUDS',
        'VAST_RUINS',
        'MUTATED_FLORA',
        'TERRAFORMED',
        'EXTREME_TEMPERATURES',
        'EXTREME_PRESSURE',
        'DIVERSE_LIFE',
        'SCARCE_LIFE',
        'FOSSILS',
        'WEAK_GRAVITY',
        'STRONG_GRAVITY',
        'CRUSHING_GRAVITY',
        'TOXIC_ATMOSPHERE',
        'CORROSIVE_ATMOSPHERE',
        'BREATHABLE_ATMOSPHERE',
        'THIN_ATMOSPHERE',
        'JOVIAN',
        'ROCKY',
        'VOLCANIC',
        'FROZEN',
        'SWAMP',
        'BARREN',
        'TEMPERATE',
        'JUNGLE',
        'OCEAN',
        'RADIOACTIVE',
        'MICRO_GRAVITY_ANOMALIES',
        'DEBRIS_CLUSTER',
        'DEEP_CRATERS',
        'SHALLOW_CRATERS',
        'UNSTABLE_COMPOSITION',
        'HOLLOWED_INTERIOR',
        'STRIPPED'
    ],
    description: 'The unique identifier of the trait.'
} as const;

export const WaypointModifierSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/WaypointModifierSymbol'
        },
        name: {
            type: 'string',
            description: 'The name of the trait.'
        },
        description: {
            type: 'string',
            description: 'A description of the trait.'
        }
    },
    required: [
        'symbol',
        'name',
        'description'
    ]
} as const;

export const WaypointModifierSymbolSchema = {
    type: 'string',
    enum: [
        'STRIPPED',
        'UNSTABLE',
        'RADIATION_LEAK',
        'CRITICAL_LIMIT',
        'CIVIL_UNREST'
    ],
    title: 'Waypoint Modifier Symbol',
    description: 'The unique identifier of the modifier.'
} as const;

export const ChartSchema = {
    type: 'object',
    properties: {
        waypointSymbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        submittedBy: {
            type: 'string',
            description: 'The agent that submitted the chart for this waypoint.'
        },
        submittedOn: {
            type: 'string',
            format: 'date-time',
            description: 'The time the chart for this waypoint was submitted.'
        }
    },
    required: [
        'waypointSymbol',
        'submittedBy',
        'submittedOn'
    ],
    description: 'The chart of a system or waypoint, which makes the location visible to other agents.'
} as const;

export const ConstructionSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            description: 'The symbol of the waypoint.'
        },
        materials: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ConstructionMaterial'
            },
            description: 'The materials required to construct the waypoint.'
        },
        isComplete: {
            type: 'boolean',
            description: 'Whether the waypoint has been constructed.'
        }
    },
    required: [
        'symbol',
        'materials',
        'isComplete'
    ],
    description: 'The construction details of a waypoint.'
} as const;

export const ConstructionMaterialSchema = {
    type: 'object',
    properties: {
        tradeSymbol: {
            $ref: '#/components/schemas/TradeSymbol'
        },
        required: {
            type: 'integer',
            description: 'The number of units required.'
        },
        fulfilled: {
            type: 'integer',
            description: 'The number of units fulfilled toward the required amount.'
        }
    },
    required: [
        'tradeSymbol',
        'required',
        'fulfilled'
    ],
    description: 'The details of the required construction materials for a given waypoint under construction.'
} as const;

export const TradeSymbolSchema = {
    type: 'string',
    enum: [
        'PRECIOUS_STONES',
        'QUARTZ_SAND',
        'SILICON_CRYSTALS',
        'AMMONIA_ICE',
        'LIQUID_HYDROGEN',
        'LIQUID_NITROGEN',
        'ICE_WATER',
        'EXOTIC_MATTER',
        'ADVANCED_CIRCUITRY',
        'GRAVITON_EMITTERS',
        'IRON',
        'IRON_ORE',
        'COPPER',
        'COPPER_ORE',
        'ALUMINUM',
        'ALUMINUM_ORE',
        'SILVER',
        'SILVER_ORE',
        'GOLD',
        'GOLD_ORE',
        'PLATINUM',
        'PLATINUM_ORE',
        'DIAMONDS',
        'URANITE',
        'URANITE_ORE',
        'MERITIUM',
        'MERITIUM_ORE',
        'HYDROCARBON',
        'ANTIMATTER',
        'FAB_MATS',
        'FERTILIZERS',
        'FABRICS',
        'FOOD',
        'JEWELRY',
        'MACHINERY',
        'FIREARMS',
        'ASSAULT_RIFLES',
        'MILITARY_EQUIPMENT',
        'EXPLOSIVES',
        'LAB_INSTRUMENTS',
        'AMMUNITION',
        'ELECTRONICS',
        'SHIP_PLATING',
        'SHIP_PARTS',
        'EQUIPMENT',
        'FUEL',
        'MEDICINE',
        'DRUGS',
        'CLOTHING',
        'MICROPROCESSORS',
        'PLASTICS',
        'POLYNUCLEOTIDES',
        'BIOCOMPOSITES',
        'QUANTUM_STABILIZERS',
        'NANOBOTS',
        'AI_MAINFRAMES',
        'QUANTUM_DRIVES',
        'ROBOTIC_DRONES',
        'CYBER_IMPLANTS',
        'GENE_THERAPEUTICS',
        'NEURAL_CHIPS',
        'MOOD_REGULATORS',
        'VIRAL_AGENTS',
        'MICRO_FUSION_GENERATORS',
        'SUPERGRAINS',
        'LASER_RIFLES',
        'HOLOGRAPHICS',
        'SHIP_SALVAGE',
        'RELIC_TECH',
        'NOVEL_LIFEFORMS',
        'BOTANICAL_SPECIMENS',
        'CULTURAL_ARTIFACTS',
        'FRAME_PROBE',
        'FRAME_DRONE',
        'FRAME_INTERCEPTOR',
        'FRAME_RACER',
        'FRAME_FIGHTER',
        'FRAME_FRIGATE',
        'FRAME_SHUTTLE',
        'FRAME_EXPLORER',
        'FRAME_MINER',
        'FRAME_LIGHT_FREIGHTER',
        'FRAME_HEAVY_FREIGHTER',
        'FRAME_TRANSPORT',
        'FRAME_DESTROYER',
        'FRAME_CRUISER',
        'FRAME_CARRIER',
        'FRAME_BULK_FREIGHTER',
        'REACTOR_SOLAR_I',
        'REACTOR_FUSION_I',
        'REACTOR_FISSION_I',
        'REACTOR_CHEMICAL_I',
        'REACTOR_ANTIMATTER_I',
        'ENGINE_IMPULSE_DRIVE_I',
        'ENGINE_ION_DRIVE_I',
        'ENGINE_ION_DRIVE_II',
        'ENGINE_HYPER_DRIVE_I',
        'MODULE_MINERAL_PROCESSOR_I',
        'MODULE_GAS_PROCESSOR_I',
        'MODULE_CARGO_HOLD_I',
        'MODULE_CARGO_HOLD_II',
        'MODULE_CARGO_HOLD_III',
        'MODULE_CREW_QUARTERS_I',
        'MODULE_ENVOY_QUARTERS_I',
        'MODULE_PASSENGER_CABIN_I',
        'MODULE_MICRO_REFINERY_I',
        'MODULE_SCIENCE_LAB_I',
        'MODULE_JUMP_DRIVE_I',
        'MODULE_JUMP_DRIVE_II',
        'MODULE_JUMP_DRIVE_III',
        'MODULE_WARP_DRIVE_I',
        'MODULE_WARP_DRIVE_II',
        'MODULE_WARP_DRIVE_III',
        'MODULE_SHIELD_GENERATOR_I',
        'MODULE_SHIELD_GENERATOR_II',
        'MODULE_ORE_REFINERY_I',
        'MODULE_FUEL_REFINERY_I',
        'MOUNT_GAS_SIPHON_I',
        'MOUNT_GAS_SIPHON_II',
        'MOUNT_GAS_SIPHON_III',
        'MOUNT_SURVEYOR_I',
        'MOUNT_SURVEYOR_II',
        'MOUNT_SURVEYOR_III',
        'MOUNT_SENSOR_ARRAY_I',
        'MOUNT_SENSOR_ARRAY_II',
        'MOUNT_SENSOR_ARRAY_III',
        'MOUNT_MINING_LASER_I',
        'MOUNT_MINING_LASER_II',
        'MOUNT_MINING_LASER_III',
        'MOUNT_LASER_CANNON_I',
        'MOUNT_MISSILE_LAUNCHER_I',
        'MOUNT_TURRET_I',
        'SHIP_PROBE',
        'SHIP_MINING_DRONE',
        'SHIP_SIPHON_DRONE',
        'SHIP_INTERCEPTOR',
        'SHIP_LIGHT_HAULER',
        'SHIP_COMMAND_FRIGATE',
        'SHIP_EXPLORER',
        'SHIP_HEAVY_FREIGHTER',
        'SHIP_LIGHT_SHUTTLE',
        'SHIP_ORE_HOUND',
        'SHIP_REFINING_FREIGHTER',
        'SHIP_SURVEYOR',
        'SHIP_BULK_FREIGHTER'
    ],
    description: 'The good\'s symbol.'
} as const;

export const ShipCargoSchema = {
    type: 'object',
    properties: {
        capacity: {
            type: 'integer',
            minimum: 0,
            description: 'The max number of items that can be stored in the cargo hold.'
        },
        units: {
            type: 'integer',
            minimum: 0,
            description: 'The number of items currently stored in the cargo hold.'
        },
        inventory: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ShipCargoItem'
            },
            description: 'The items currently in the cargo hold.'
        }
    },
    required: [
        'capacity',
        'units',
        'inventory'
    ],
    description: 'Ship cargo details.'
} as const;

export const ShipCargoItemSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/TradeSymbol'
        },
        name: {
            type: 'string',
            description: 'The name of the cargo item type.'
        },
        description: {
            type: 'string',
            description: 'The description of the cargo item type.'
        },
        units: {
            type: 'integer',
            description: 'The number of units of the cargo item.',
            minimum: 1
        }
    },
    required: [
        'symbol',
        'name',
        'description',
        'units'
    ],
    description: 'The type of cargo item and the number of units.'
} as const;

export const MarketSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            description: 'The symbol of the market. The symbol is the same as the waypoint where the market is located.'
        },
        exports: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TradeGood'
            },
            description: 'The list of goods that are exported from this market.'
        },
        imports: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TradeGood'
            },
            description: 'The list of goods that are sought as imports in this market.'
        },
        exchange: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TradeGood'
            },
            description: 'The list of goods that are bought and sold between agents at this market.'
        },
        transactions: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MarketTransaction'
            },
            description: 'The list of recent transactions at this market. Visible only when a ship is present at the market.'
        },
        tradeGoods: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MarketTradeGood'
            },
            description: 'The list of goods that are traded at this market. Visible only when a ship is present at the market.'
        }
    },
    required: [
        'symbol',
        'exports',
        'imports',
        'exchange'
    ],
    description: 'Market details.'
} as const;

export const TradeGoodSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/TradeSymbol'
        },
        name: {
            type: 'string',
            description: 'The name of the good.'
        },
        description: {
            type: 'string',
            description: 'The description of the good.'
        }
    },
    required: [
        'symbol',
        'name',
        'description'
    ],
    description: 'A good that can be traded for other goods or currency.'
} as const;

export const MarketTransactionSchema = {
    type: 'object',
    properties: {
        waypointSymbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        shipSymbol: {
            type: 'string',
            description: 'The symbol of the ship that made the transaction.'
        },
        tradeSymbol: {
            type: 'string',
            description: 'The symbol of the trade good.'
        },
        type: {
            type: 'string',
            enum: [
                'PURCHASE',
                'SELL'
            ],
            description: 'The type of transaction.'
        },
        units: {
            type: 'integer',
            minimum: 0,
            description: 'The number of units of the transaction.'
        },
        pricePerUnit: {
            type: 'integer',
            minimum: 0,
            description: 'The price per unit of the transaction.'
        },
        totalPrice: {
            type: 'integer',
            minimum: 0,
            description: 'The total price of the transaction.'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'The timestamp of the transaction.'
        }
    },
    required: [
        'waypointSymbol',
        'shipSymbol',
        'tradeSymbol',
        'type',
        'units',
        'pricePerUnit',
        'totalPrice',
        'timestamp'
    ],
    description: 'Result of a transaction with a market.'
} as const;

export const MarketTradeGoodSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/TradeSymbol'
        },
        type: {
            type: 'string',
            enum: [
                'EXPORT',
                'IMPORT',
                'EXCHANGE'
            ],
            description: 'The type of trade good (export, import, or exchange).'
        },
        tradeVolume: {
            type: 'integer',
            minimum: 1,
            description: 'This is the maximum number of units that can be purchased or sold at this market in a single trade for this good. Trade volume also gives an indication of price volatility. A market with a low trade volume will have large price swings, while high trade volume will be more resilient to price changes.'
        },
        supply: {
            $ref: '#/components/schemas/SupplyLevel'
        },
        activity: {
            $ref: '#/components/schemas/ActivityLevel'
        },
        purchasePrice: {
            type: 'integer',
            minimum: 0,
            description: 'The price at which this good can be purchased from the market.'
        },
        sellPrice: {
            type: 'integer',
            minimum: 0,
            description: 'The price at which this good can be sold to the market.'
        }
    },
    required: [
        'symbol',
        'type',
        'tradeVolume',
        'supply',
        'purchasePrice',
        'sellPrice'
    ]
} as const;

export const SupplyLevelSchema = {
    type: 'string',
    enum: [
        'SCARCE',
        'LIMITED',
        'MODERATE',
        'HIGH',
        'ABUNDANT'
    ],
    description: 'The supply level of a trade good.'
} as const;

export const ActivityLevelSchema = {
    type: 'string',
    enum: [
        'WEAK',
        'GROWING',
        'STRONG',
        'RESTRICTED'
    ],
    description: 'The activity level of a trade good. If the good is an import, this represents how strong consumption is. If the good is an export, this represents how strong the production is for the good. When activity is strong, consumption or production is near maximum capacity. When activity is weak, consumption or production is near minimum capacity.',
    'x-enumDescriptions': {
        GROWING: 'Represents increasing activity in production or consumption, suggesting a developing market.',
        RESTRICTED: 'Reflects a bottleneck in production or consumption, possibly due to a lack of supply or demand in related goods.',
        STRONG: 'Signifies high levels of production or consumption. Indicates a healthy and active market with high demand or supply.',
        WEAK: 'Indicates very low production or consumption activity. This may suggest a surplus in supply or a lack of demand.'
    }
} as const;

export const JumpGateSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        connections: {
            type: 'array',
            items: {
                type: 'string',
                description: 'The symbol of the waypoint that has a corresponding gate.'
            },
            description: 'All the gates that are connected to this waypoint.'
        }
    },
    required: [
        'symbol',
        'connections'
    ],
    description: 'Details of a jump gate waypoint.'
} as const;

export const ShipyardSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.'
        },
        shipTypes: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    type: {
                        $ref: '#/components/schemas/ShipType'
                    }
                },
                required: [
                    'type'
                ]
            },
            description: 'The list of ship types available for purchase at this shipyard.'
        },
        transactions: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ShipyardTransaction'
            },
            description: 'The list of recent transactions at this shipyard.'
        },
        ships: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ShipyardShip'
            },
            description: 'The ships that are currently available for purchase at the shipyard.'
        },
        modificationsFee: {
            type: 'integer',
            description: 'The fee to modify a ship at this shipyard. This includes installing or removing modules and mounts on a ship. In the case of mounts, the fee is a flat rate per mount. In the case of modules, the fee is per slot the module occupies.'
        }
    },
    required: [
        'symbol',
        'shipTypes',
        'modificationsFee'
    ],
    description: 'Shipyard details.'
} as const;

export const ShipTypeSchema = {
    type: 'string',
    enum: [
        'SHIP_PROBE',
        'SHIP_MINING_DRONE',
        'SHIP_SIPHON_DRONE',
        'SHIP_INTERCEPTOR',
        'SHIP_LIGHT_HAULER',
        'SHIP_COMMAND_FRIGATE',
        'SHIP_EXPLORER',
        'SHIP_HEAVY_FREIGHTER',
        'SHIP_LIGHT_SHUTTLE',
        'SHIP_ORE_HOUND',
        'SHIP_REFINING_FREIGHTER',
        'SHIP_SURVEYOR',
        'SHIP_BULK_FREIGHTER'
    ],
    description: 'Type of ship'
} as const;

export const ShipyardTransactionSchema = {
    type: 'object',
    properties: {
        waypointSymbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        shipSymbol: {
            type: 'string',
            description: 'The symbol of the ship type (e.g. SHIP_MINING_DRONE) that was the subject of the transaction. Contrary to what the name implies, this is NOT the symbol of the ship that was purchased.',
            deprecated: true
        },
        shipType: {
            type: 'string',
            description: 'The symbol of the ship type (e.g. SHIP_MINING_DRONE) that was the subject of the transaction.'
        },
        price: {
            type: 'integer',
            minimum: 0,
            description: 'The price of the transaction.'
        },
        agentSymbol: {
            type: 'string',
            description: 'The symbol of the agent that made the transaction.'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'The timestamp of the transaction.'
        }
    },
    required: [
        'waypointSymbol',
        'shipSymbol',
        'shipType',
        'price',
        'agentSymbol',
        'timestamp'
    ],
    description: 'Results of a transaction with a shipyard.'
} as const;

export const ShipyardShipSchema = {
    type: 'object',
    properties: {
        type: {
            $ref: '#/components/schemas/ShipType'
        },
        name: {
            type: 'string',
            description: 'Name of the ship.'
        },
        description: {
            type: 'string',
            description: 'Description of the ship.'
        },
        activity: {
            $ref: '#/components/schemas/ActivityLevel'
        },
        supply: {
            $ref: '#/components/schemas/SupplyLevel'
        },
        purchasePrice: {
            type: 'integer',
            description: 'The purchase price of the ship.'
        },
        frame: {
            $ref: '#/components/schemas/ShipFrame'
        },
        reactor: {
            $ref: '#/components/schemas/ShipReactor'
        },
        engine: {
            $ref: '#/components/schemas/ShipEngine'
        },
        modules: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ShipModule'
            },
            description: 'Modules installed in this ship.'
        },
        mounts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ShipMount'
            },
            description: 'Mounts installed in this ship.'
        },
        crew: {
            type: 'object',
            properties: {
                required: {
                    type: 'integer',
                    description: 'The minimum number of crew members required to maintain the ship.'
                },
                capacity: {
                    type: 'integer',
                    description: 'The maximum number of crew members the ship can support.'
                }
            },
            required: [
                'required',
                'capacity'
            ]
        }
    },
    required: [
        'type',
        'name',
        'description',
        'supply',
        'purchasePrice',
        'frame',
        'reactor',
        'engine',
        'modules',
        'mounts',
        'crew'
    ],
    description: 'Ship details available at a shipyard.'
} as const;

export const ShipFrameSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            enum: [
                'FRAME_PROBE',
                'FRAME_DRONE',
                'FRAME_INTERCEPTOR',
                'FRAME_RACER',
                'FRAME_FIGHTER',
                'FRAME_FRIGATE',
                'FRAME_SHUTTLE',
                'FRAME_EXPLORER',
                'FRAME_MINER',
                'FRAME_LIGHT_FREIGHTER',
                'FRAME_HEAVY_FREIGHTER',
                'FRAME_TRANSPORT',
                'FRAME_DESTROYER',
                'FRAME_CRUISER',
                'FRAME_CARRIER',
                'FRAME_BULK_FREIGHTER'
            ],
            description: 'Symbol of the frame.'
        },
        name: {
            type: 'string',
            description: 'Name of the frame.'
        },
        condition: {
            $ref: '#/components/schemas/ShipComponentCondition'
        },
        integrity: {
            $ref: '#/components/schemas/ShipComponentIntegrity'
        },
        description: {
            type: 'string',
            description: 'Description of the frame.'
        },
        moduleSlots: {
            type: 'integer',
            minimum: 0,
            description: 'The amount of slots that can be dedicated to modules installed in the ship. Each installed module take up a number of slots, and once there are no more slots, no new modules can be installed.'
        },
        mountingPoints: {
            type: 'integer',
            minimum: 0,
            description: 'The amount of slots that can be dedicated to mounts installed in the ship. Each installed mount takes up a number of points, and once there are no more points remaining, no new mounts can be installed.'
        },
        fuelCapacity: {
            type: 'integer',
            minimum: 0,
            description: 'The maximum amount of fuel that can be stored in this ship. When refueling, the ship will be refueled to this amount.'
        },
        requirements: {
            $ref: '#/components/schemas/ShipRequirements'
        },
        quality: {
            $ref: '#/components/schemas/ShipComponentQuality'
        }
    },
    required: [
        'symbol',
        'name',
        'condition',
        'integrity',
        'description',
        'moduleSlots',
        'mountingPoints',
        'fuelCapacity',
        'requirements',
        'quality'
    ],
    description: 'The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.'
} as const;

export const ShipComponentConditionSchema = {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description: 'The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.',
    format: 'double'
} as const;

export const ShipComponentIntegritySchema = {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description: 'The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.',
    format: 'double'
} as const;

export const ShipRequirementsSchema = {
    type: 'object',
    properties: {
        power: {
            type: 'integer',
            description: 'The amount of power required from the reactor.'
        },
        crew: {
            type: 'integer',
            description: 'The number of crew required for operation.'
        },
        slots: {
            type: 'integer',
            description: 'The number of module slots required for installation.'
        }
    },
    description: 'The requirements for installation on a ship'
} as const;

export const ShipComponentQualitySchema = {
    type: 'number',
    description: 'The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.',
    format: 'integer'
} as const;

export const ShipReactorSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            enum: [
                'REACTOR_SOLAR_I',
                'REACTOR_FUSION_I',
                'REACTOR_FISSION_I',
                'REACTOR_CHEMICAL_I',
                'REACTOR_ANTIMATTER_I'
            ],
            description: 'Symbol of the reactor.'
        },
        name: {
            type: 'string',
            description: 'Name of the reactor.'
        },
        condition: {
            $ref: '#/components/schemas/ShipComponentCondition'
        },
        integrity: {
            $ref: '#/components/schemas/ShipComponentIntegrity'
        },
        description: {
            type: 'string',
            description: 'Description of the reactor.'
        },
        powerOutput: {
            type: 'integer',
            minimum: 1,
            description: 'The amount of power provided by this reactor. The more power a reactor provides to the ship, the lower the cooldown it gets when using a module or mount that taxes the ship\'s power.'
        },
        requirements: {
            $ref: '#/components/schemas/ShipRequirements'
        },
        quality: {
            $ref: '#/components/schemas/ShipComponentQuality'
        }
    },
    required: [
        'symbol',
        'name',
        'condition',
        'integrity',
        'description',
        'powerOutput',
        'requirements',
        'quality'
    ],
    description: 'The reactor of the ship. The reactor is responsible for powering the ship\'s systems and weapons.'
} as const;

export const ShipEngineSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            enum: [
                'ENGINE_IMPULSE_DRIVE_I',
                'ENGINE_ION_DRIVE_I',
                'ENGINE_ION_DRIVE_II',
                'ENGINE_HYPER_DRIVE_I'
            ],
            description: 'The symbol of the engine.'
        },
        name: {
            type: 'string',
            description: 'The name of the engine.'
        },
        condition: {
            $ref: '#/components/schemas/ShipComponentCondition'
        },
        integrity: {
            $ref: '#/components/schemas/ShipComponentIntegrity'
        },
        description: {
            type: 'string',
            description: 'The description of the engine.'
        },
        speed: {
            type: 'integer',
            minimum: 1,
            description: 'The speed stat of this engine. The higher the speed, the faster a ship can travel from one point to another. Reduces the time of arrival when navigating the ship.'
        },
        requirements: {
            $ref: '#/components/schemas/ShipRequirements'
        },
        quality: {
            $ref: '#/components/schemas/ShipComponentQuality'
        }
    },
    required: [
        'symbol',
        'name',
        'condition',
        'integrity',
        'description',
        'speed',
        'requirements',
        'quality'
    ],
    description: 'The engine determines how quickly a ship travels between waypoints.'
} as const;

export const ShipModuleSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            enum: [
                'MODULE_MINERAL_PROCESSOR_I',
                'MODULE_GAS_PROCESSOR_I',
                'MODULE_CARGO_HOLD_I',
                'MODULE_CARGO_HOLD_II',
                'MODULE_CARGO_HOLD_III',
                'MODULE_CREW_QUARTERS_I',
                'MODULE_ENVOY_QUARTERS_I',
                'MODULE_PASSENGER_CABIN_I',
                'MODULE_MICRO_REFINERY_I',
                'MODULE_ORE_REFINERY_I',
                'MODULE_FUEL_REFINERY_I',
                'MODULE_SCIENCE_LAB_I',
                'MODULE_JUMP_DRIVE_I',
                'MODULE_JUMP_DRIVE_II',
                'MODULE_JUMP_DRIVE_III',
                'MODULE_WARP_DRIVE_I',
                'MODULE_WARP_DRIVE_II',
                'MODULE_WARP_DRIVE_III',
                'MODULE_SHIELD_GENERATOR_I',
                'MODULE_SHIELD_GENERATOR_II'
            ],
            description: 'The symbol of the module.'
        },
        name: {
            type: 'string',
            description: 'Name of this module.'
        },
        description: {
            type: 'string',
            description: 'Description of this module.'
        },
        capacity: {
            type: 'integer',
            minimum: 0,
            description: 'Modules that provide capacity, such as cargo hold or crew quarters will show this value to denote how much of a bonus the module grants.'
        },
        range: {
            type: 'integer',
            minimum: 0,
            description: 'Modules that have a range will such as a sensor array show this value to denote how far can the module reach with its capabilities.'
        },
        requirements: {
            $ref: '#/components/schemas/ShipRequirements'
        }
    },
    required: [
        'symbol',
        'name',
        'description',
        'requirements'
    ],
    description: 'A module can be installed in a ship and provides a set of capabilities such as storage space or quarters for crew. Module installations are permanent.'
} as const;

export const ShipMountSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            enum: [
                'MOUNT_GAS_SIPHON_I',
                'MOUNT_GAS_SIPHON_II',
                'MOUNT_GAS_SIPHON_III',
                'MOUNT_SURVEYOR_I',
                'MOUNT_SURVEYOR_II',
                'MOUNT_SURVEYOR_III',
                'MOUNT_SENSOR_ARRAY_I',
                'MOUNT_SENSOR_ARRAY_II',
                'MOUNT_SENSOR_ARRAY_III',
                'MOUNT_MINING_LASER_I',
                'MOUNT_MINING_LASER_II',
                'MOUNT_MINING_LASER_III',
                'MOUNT_LASER_CANNON_I',
                'MOUNT_MISSILE_LAUNCHER_I',
                'MOUNT_TURRET_I'
            ],
            description: 'Symbol of this mount.'
        },
        name: {
            type: 'string',
            description: 'Name of this mount.'
        },
        description: {
            type: 'string',
            description: 'Description of this mount.'
        },
        strength: {
            type: 'integer',
            minimum: 0,
            description: 'Mounts that have this value, such as mining lasers, denote how powerful this mount\'s capabilities are.'
        },
        deposits: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'QUARTZ_SAND',
                    'SILICON_CRYSTALS',
                    'PRECIOUS_STONES',
                    'ICE_WATER',
                    'AMMONIA_ICE',
                    'IRON_ORE',
                    'COPPER_ORE',
                    'SILVER_ORE',
                    'ALUMINUM_ORE',
                    'GOLD_ORE',
                    'PLATINUM_ORE',
                    'DIAMONDS',
                    'URANITE_ORE',
                    'MERITIUM_ORE'
                ]
            },
            description: 'Mounts that have this value denote what goods can be produced from using the mount.'
        },
        requirements: {
            $ref: '#/components/schemas/ShipRequirements'
        }
    },
    required: [
        'symbol',
        'name',
        'description',
        'requirements'
    ],
    description: 'A mount is installed on the exterier of a ship.'
} as const;

export const ContractSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            minLength: 1,
            description: 'ID of the contract.'
        },
        factionSymbol: {
            type: 'string',
            description: 'The symbol of the faction that this contract is for.',
            minLength: 1
        },
        type: {
            type: 'string',
            enum: [
                'PROCUREMENT',
                'TRANSPORT',
                'SHUTTLE'
            ],
            description: 'Type of contract.'
        },
        terms: {
            $ref: '#/components/schemas/ContractTerms'
        },
        accepted: {
            type: 'boolean',
            default: false,
            description: 'Whether the contract has been accepted by the agent'
        },
        fulfilled: {
            type: 'boolean',
            default: false,
            description: 'Whether the contract has been fulfilled'
        },
        expiration: {
            type: 'string',
            format: 'date-time',
            description: 'Deprecated in favor of deadlineToAccept',
            deprecated: true
        },
        deadlineToAccept: {
            type: 'string',
            format: 'date-time',
            description: 'The time at which the contract is no longer available to be accepted'
        }
    },
    required: [
        'id',
        'factionSymbol',
        'type',
        'terms',
        'accepted',
        'fulfilled',
        'expiration'
    ],
    description: 'Contract details.'
} as const;

export const ContractTermsSchema = {
    type: 'object',
    properties: {
        deadline: {
            type: 'string',
            format: 'date-time',
            description: 'The deadline for the contract.'
        },
        payment: {
            $ref: '#/components/schemas/ContractPayment'
        },
        deliver: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ContractDeliverGood'
            },
            description: 'The cargo that needs to be delivered to fulfill the contract.'
        }
    },
    required: [
        'deadline',
        'payment'
    ],
    description: 'The terms to fulfill the contract.'
} as const;

export const ContractPaymentSchema = {
    type: 'object',
    properties: {
        onAccepted: {
            type: 'integer',
            description: 'The amount of credits received up front for accepting the contract.'
        },
        onFulfilled: {
            type: 'integer',
            description: 'The amount of credits received when the contract is fulfilled.'
        }
    },
    required: [
        'onAccepted',
        'onFulfilled'
    ],
    description: 'Payments for the contract.'
} as const;

export const ContractDeliverGoodSchema = {
    type: 'object',
    properties: {
        tradeSymbol: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the trade good to deliver.'
        },
        destinationSymbol: {
            type: 'string',
            minLength: 1,
            description: 'The destination where goods need to be delivered.'
        },
        unitsRequired: {
            type: 'integer',
            description: 'The number of units that need to be delivered on this contract.'
        },
        unitsFulfilled: {
            type: 'integer',
            description: 'The number of units fulfilled on this contract.'
        }
    },
    required: [
        'tradeSymbol',
        'destinationSymbol',
        'unitsRequired',
        'unitsFulfilled'
    ],
    description: 'The details of a delivery contract. Includes the type of good, units needed, and the destination.'
} as const;

export const AgentSchema = {
    type: 'object',
    properties: {
        accountId: {
            type: 'string',
            description: 'Account ID that is tied to this agent. Only included on your own agent.',
            minLength: 1
        },
        symbol: {
            type: 'string',
            description: 'Symbol of the agent.',
            maxLength: 14,
            minLength: 3
        },
        headquarters: {
            type: 'string',
            description: 'The headquarters of the agent.',
            minLength: 1
        },
        credits: {
            type: 'integer',
            description: 'The number of credits the agent has available. Credits can be negative if funds have been overdrawn.',
            format: 'int64'
        },
        startingFaction: {
            type: 'string',
            description: 'The faction the agent started with.',
            minLength: 1
        },
        shipCount: {
            type: 'integer',
            description: 'How many ships are owned by the agent.'
        }
    },
    required: [
        'accountId',
        'symbol',
        'headquarters',
        'credits',
        'startingFaction',
        'shipCount'
    ],
    description: 'Agent details.'
} as const;

export const AgentEventSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        type: {
            type: 'string'
        },
        message: {
            type: 'string'
        },
        data: {},
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: [
        'id',
        'type',
        'message',
        'createdAt'
    ],
    description: 'Agent event details.'
} as const;

export const ShipSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            description: 'The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]-[HEX_ID]`'
        },
        registration: {
            $ref: '#/components/schemas/ShipRegistration'
        },
        nav: {
            $ref: '#/components/schemas/ShipNav'
        },
        crew: {
            $ref: '#/components/schemas/ShipCrew'
        },
        frame: {
            $ref: '#/components/schemas/ShipFrame'
        },
        reactor: {
            $ref: '#/components/schemas/ShipReactor'
        },
        engine: {
            $ref: '#/components/schemas/ShipEngine'
        },
        modules: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ShipModule'
            },
            description: 'Modules installed in this ship.'
        },
        mounts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ShipMount'
            },
            description: 'Mounts installed in this ship.'
        },
        cargo: {
            $ref: '#/components/schemas/ShipCargo'
        },
        fuel: {
            $ref: '#/components/schemas/ShipFuel'
        },
        cooldown: {
            $ref: '#/components/schemas/Cooldown'
        }
    },
    required: [
        'symbol',
        'registration',
        'nav',
        'crew',
        'frame',
        'reactor',
        'engine',
        'modules',
        'mounts',
        'cargo',
        'fuel',
        'cooldown'
    ],
    description: 'Ship details.'
} as const;

export const ShipRegistrationSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            description: 'The agent\'s registered name of the ship'
        },
        factionSymbol: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the faction the ship is registered with'
        },
        role: {
            $ref: '#/components/schemas/ShipRole'
        }
    },
    required: [
        'name',
        'factionSymbol',
        'role'
    ],
    description: 'The public registration information of the ship'
} as const;

export const ShipRoleSchema = {
    type: 'string',
    enum: [
        'FABRICATOR',
        'HARVESTER',
        'HAULER',
        'INTERCEPTOR',
        'EXCAVATOR',
        'TRANSPORT',
        'REPAIR',
        'SURVEYOR',
        'COMMAND',
        'CARRIER',
        'PATROL',
        'SATELLITE',
        'EXPLORER',
        'REFINERY'
    ],
    description: 'The registered role of the ship'
} as const;

export const ShipNavSchema = {
    type: 'object',
    properties: {
        systemSymbol: {
            $ref: '#/components/schemas/SystemSymbol'
        },
        waypointSymbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        route: {
            $ref: '#/components/schemas/ShipNavRoute'
        },
        status: {
            $ref: '#/components/schemas/ShipNavStatus'
        },
        flightMode: {
            $ref: '#/components/schemas/ShipNavFlightMode'
        }
    },
    required: [
        'systemSymbol',
        'waypointSymbol',
        'route',
        'status',
        'flightMode'
    ],
    description: 'The navigation information of the ship.'
} as const;

export const ShipNavRouteSchema = {
    type: 'object',
    properties: {
        destination: {
            $ref: '#/components/schemas/ShipNavRouteWaypoint'
        },
        origin: {
            $ref: '#/components/schemas/ShipNavRouteWaypoint'
        },
        departureTime: {
            type: 'string',
            format: 'date-time',
            description: 'The date time of the ship\'s departure.'
        },
        arrival: {
            type: 'string',
            format: 'date-time',
            description: 'The date time of the ship\'s arrival. If the ship is in-transit, this is the expected time of arrival.'
        }
    },
    required: [
        'destination',
        'origin',
        'departureTime',
        'arrival'
    ],
    description: 'The routing information for the ship\'s most recent transit or current location.'
} as const;

export const ShipNavRouteWaypointSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the waypoint.'
        },
        type: {
            $ref: '#/components/schemas/WaypointType'
        },
        systemSymbol: {
            $ref: '#/components/schemas/SystemSymbol'
        },
        x: {
            type: 'integer',
            description: 'Position in the universe in the x axis.'
        },
        y: {
            type: 'integer',
            description: 'Position in the universe in the y axis.'
        }
    },
    required: [
        'symbol',
        'type',
        'systemSymbol',
        'x',
        'y'
    ],
    description: 'The destination or departure of a ships nav route.'
} as const;

export const ShipNavStatusSchema = {
    type: 'string',
    enum: [
        'IN_TRANSIT',
        'IN_ORBIT',
        'DOCKED'
    ],
    description: 'The current status of the ship'
} as const;

export const ShipNavFlightModeSchema = {
    type: 'string',
    enum: [
        'DRIFT',
        'STEALTH',
        'CRUISE',
        'BURN'
    ],
    default: 'CRUISE',
    description: 'The ship\'s set speed when traveling between waypoints or systems.'
} as const;

export const ShipCrewSchema = {
    type: 'object',
    properties: {
        current: {
            type: 'integer',
            description: 'The current number of crew members on the ship.'
        },
        required: {
            type: 'integer',
            description: 'The minimum number of crew members required to maintain the ship.'
        },
        capacity: {
            type: 'integer',
            description: 'The maximum number of crew members the ship can support.'
        },
        rotation: {
            type: 'string',
            enum: [
                'STRICT',
                'RELAXED'
            ],
            default: 'STRICT',
            description: 'The rotation of crew shifts. A stricter shift improves the ship\'s performance. A more relaxed shift improves the crew\'s morale.'
        },
        morale: {
            type: 'integer',
            minimum: 0,
            maximum: 100,
            description: 'A rough measure of the crew\'s morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents.'
        },
        wages: {
            type: 'integer',
            minimum: 0,
            description: 'The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint.'
        }
    },
    required: [
        'current',
        'required',
        'capacity',
        'rotation',
        'morale',
        'wages'
    ],
    description: 'The ship\'s crew service and maintain the ship\'s systems and equipment.'
} as const;

export const ShipFuelSchema = {
    type: 'object',
    properties: {
        current: {
            type: 'integer',
            minimum: 0,
            description: 'The current amount of fuel in the ship\'s tanks.'
        },
        capacity: {
            type: 'integer',
            minimum: 0,
            description: 'The maximum amount of fuel the ship\'s tanks can hold.'
        },
        consumed: {
            type: 'object',
            properties: {
                amount: {
                    type: 'integer',
                    minimum: 0,
                    description: 'The amount of fuel consumed by the most recent transit or action.'
                },
                timestamp: {
                    type: 'string',
                    format: 'date-time',
                    description: 'The time at which the fuel was consumed.'
                }
            },
            required: [
                'amount',
                'timestamp'
            ],
            description: 'An object that only shows up when an action has consumed fuel in the process. Shows the fuel consumption data.'
        }
    },
    required: [
        'current',
        'capacity'
    ],
    description: 'Details of the ship\'s fuel tanks including how much fuel was consumed during the last transit or action.'
} as const;

export const CooldownSchema = {
    type: 'object',
    properties: {
        shipSymbol: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the ship that is on cooldown'
        },
        totalSeconds: {
            type: 'integer',
            minimum: 0,
            description: 'The total duration of the cooldown in seconds'
        },
        remainingSeconds: {
            type: 'integer',
            minimum: 0,
            description: 'The remaining duration of the cooldown in seconds'
        },
        expiration: {
            type: 'string',
            format: 'date-time',
            description: 'The date and time when the cooldown expires in ISO 8601 format'
        }
    },
    required: [
        'shipSymbol',
        'totalSeconds',
        'remainingSeconds'
    ],
    description: 'A cooldown is a period of time in which a ship cannot perform certain actions.'
} as const;

export const ChartTransactionSchema = {
    type: 'object',
    properties: {
        waypointSymbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        shipSymbol: {
            type: 'string',
            description: 'The symbol of the ship.'
        },
        totalPrice: {
            type: 'integer',
            minimum: 0,
            description: 'The total price of the transaction.'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'The timestamp of the transaction.'
        }
    },
    required: [
        'waypointSymbol',
        'shipSymbol',
        'totalPrice',
        'timestamp'
    ],
    description: 'Result of a chart transaction.'
} as const;

export const ExtractionSchema = {
    type: 'object',
    properties: {
        shipSymbol: {
            type: 'string',
            minLength: 1,
            description: 'Symbol of the ship that executed the extraction.'
        },
        yield: {
            $ref: '#/components/schemas/ExtractionYield'
        }
    },
    required: [
        'shipSymbol',
        'yield'
    ],
    description: 'Extraction details.'
} as const;

export const ExtractionYieldSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/TradeSymbol'
        },
        units: {
            type: 'integer',
            description: 'The number of units extracted that were placed into the ship\'s cargo hold.'
        }
    },
    required: [
        'symbol',
        'units'
    ],
    description: 'A yield from the extraction operation.'
} as const;

export const ShipConditionEventSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            enum: [
                'REACTOR_OVERLOAD',
                'ENERGY_SPIKE_FROM_MINERAL',
                'SOLAR_FLARE_INTERFERENCE',
                'COOLANT_LEAK',
                'POWER_DISTRIBUTION_FLUCTUATION',
                'MAGNETIC_FIELD_DISRUPTION',
                'HULL_MICROMETEORITE_STRIKES',
                'STRUCTURAL_STRESS_FRACTURES',
                'CORROSIVE_MINERAL_CONTAMINATION',
                'THERMAL_EXPANSION_MISMATCH',
                'VIBRATION_DAMAGE_FROM_DRILLING',
                'ELECTROMAGNETIC_FIELD_INTERFERENCE',
                'IMPACT_WITH_EXTRACTED_DEBRIS',
                'FUEL_EFFICIENCY_DEGRADATION',
                'COOLANT_SYSTEM_AGEING',
                'DUST_MICROABRASIONS',
                'THRUSTER_NOZZLE_WEAR',
                'EXHAUST_PORT_CLOGGING',
                'BEARING_LUBRICATION_FADE',
                'SENSOR_CALIBRATION_DRIFT',
                'HULL_MICROMETEORITE_DAMAGE',
                'SPACE_DEBRIS_COLLISION',
                'THERMAL_STRESS',
                'VIBRATION_OVERLOAD',
                'PRESSURE_DIFFERENTIAL_STRESS',
                'ELECTROMAGNETIC_SURGE_EFFECTS',
                'ATMOSPHERIC_ENTRY_HEAT'
            ],
            description: 'The symbol of the event that occurred.'
        },
        component: {
            type: 'string',
            enum: [
                'FRAME',
                'REACTOR',
                'ENGINE'
            ]
        },
        name: {
            type: 'string',
            description: 'The name of the event.'
        },
        description: {
            type: 'string',
            description: 'A description of the event.'
        }
    },
    required: [
        'symbol',
        'component',
        'name',
        'description'
    ],
    description: 'An event that represents damage or wear to a ship\'s reactor, frame, or engine, reducing the condition of the ship.'
} as const;

export const SurveySchema = {
    type: 'object',
    properties: {
        signature: {
            type: 'string',
            minLength: 1,
            description: 'A unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.'
        },
        symbol: {
            type: 'string',
            minLength: 1,
            description: 'The symbol of the waypoint that this survey is for.'
        },
        deposits: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/SurveyDeposit'
            },
            description: 'A list of deposits that can be found at this location. A ship will extract one of these deposits when using this survey in an extraction request. If multiple deposits of the same type are present, the chance of extracting that deposit is increased.'
        },
        expiration: {
            type: 'string',
            format: 'date-time',
            description: 'The date and time when the survey expires. After this date and time, the survey will no longer be available for extraction.'
        },
        size: {
            $ref: '#/components/schemas/SurveySize'
        }
    },
    required: [
        'signature',
        'symbol',
        'deposits',
        'expiration',
        'size'
    ],
    description: 'A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.'
} as const;

export const SurveyDepositSchema = {
    type: 'object',
    properties: {
        symbol: {
            description: 'The symbol of the deposit.',
            allOf: [
                {
                    $ref: '#/components/schemas/TradeSymbol'
                }
            ]
        }
    },
    required: [
        'symbol'
    ],
    description: 'A surveyed deposit of a mineral or resource available for extraction.'
} as const;

export const SurveySizeSchema = {
    type: 'string',
    enum: [
        'SMALL',
        'MODERATE',
        'LARGE'
    ],
    description: 'The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.'
} as const;

export const ScannedSystemSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            minLength: 1,
            description: 'Symbol of the system.'
        },
        sectorSymbol: {
            type: 'string',
            minLength: 1,
            description: 'Symbol of the system\'s sector.'
        },
        type: {
            $ref: '#/components/schemas/SystemType'
        },
        x: {
            type: 'integer',
            description: 'Position in the universe in the x axis.'
        },
        y: {
            type: 'integer',
            description: 'Position in the universe in the y axis.'
        },
        distance: {
            type: 'integer',
            description: 'The system\'s distance from the scanning ship.'
        }
    },
    required: [
        'symbol',
        'sectorSymbol',
        'type',
        'x',
        'y',
        'distance'
    ],
    description: 'Details of a system was that scanned.'
} as const;

export const ScannedWaypointSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        type: {
            $ref: '#/components/schemas/WaypointType'
        },
        systemSymbol: {
            $ref: '#/components/schemas/SystemSymbol'
        },
        x: {
            type: 'integer',
            description: 'Position in the universe in the x axis.'
        },
        y: {
            type: 'integer',
            description: 'Position in the universe in the y axis.'
        },
        orbitals: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/WaypointOrbital'
            },
            description: 'List of waypoints that orbit this waypoint.'
        },
        faction: {
            $ref: '#/components/schemas/WaypointFaction'
        },
        traits: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/WaypointTrait'
            },
            description: 'The traits of the waypoint.'
        },
        chart: {
            $ref: '#/components/schemas/Chart'
        }
    },
    required: [
        'symbol',
        'type',
        'systemSymbol',
        'x',
        'y',
        'orbitals',
        'traits'
    ],
    description: 'A waypoint that was scanned by a ship.'
} as const;

export const ScannedShipSchema = {
    type: 'object',
    properties: {
        symbol: {
            type: 'string',
            description: 'The globally unique identifier of the ship.'
        },
        registration: {
            $ref: '#/components/schemas/ShipRegistration'
        },
        nav: {
            $ref: '#/components/schemas/ShipNav'
        },
        frame: {
            type: 'object',
            properties: {
                symbol: {
                    type: 'string',
                    description: 'The symbol of the frame.'
                }
            },
            required: [
                'symbol'
            ],
            description: 'The frame of the ship.'
        },
        reactor: {
            type: 'object',
            properties: {
                symbol: {
                    type: 'string',
                    description: 'The symbol of the reactor.'
                }
            },
            required: [
                'symbol'
            ],
            description: 'The reactor of the ship.'
        },
        engine: {
            type: 'object',
            properties: {
                symbol: {
                    type: 'string',
                    description: 'The symbol of the engine.'
                }
            },
            required: [
                'symbol'
            ],
            description: 'The engine of the ship.'
        },
        mounts: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    symbol: {
                        type: 'string',
                        description: 'The symbol of the mount.'
                    }
                },
                required: [
                    'symbol'
                ]
            },
            description: 'List of mounts installed in the ship.'
        }
    },
    required: [
        'symbol',
        'registration',
        'nav',
        'engine'
    ],
    description: 'The ship that was scanned. Details include information about the ship that could be detected by the scanner.'
} as const;

export const ScrapTransactionSchema = {
    type: 'object',
    properties: {
        waypointSymbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        shipSymbol: {
            type: 'string',
            description: 'The symbol of the ship.'
        },
        totalPrice: {
            type: 'integer',
            minimum: 0,
            description: 'The total price of the transaction.'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'The timestamp of the transaction.'
        }
    },
    required: [
        'waypointSymbol',
        'shipSymbol',
        'totalPrice',
        'timestamp'
    ],
    description: 'Result of a scrap transaction.'
} as const;

export const RepairTransactionSchema = {
    type: 'object',
    properties: {
        waypointSymbol: {
            $ref: '#/components/schemas/WaypointSymbol'
        },
        shipSymbol: {
            type: 'string',
            description: 'The symbol of the ship.'
        },
        totalPrice: {
            type: 'integer',
            minimum: 0,
            description: 'The total price of the transaction.'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'The timestamp of the transaction.'
        }
    },
    required: [
        'waypointSymbol',
        'shipSymbol',
        'totalPrice',
        'timestamp'
    ],
    description: 'Result of a repair transaction.'
} as const;

export const SiphonSchema = {
    type: 'object',
    properties: {
        shipSymbol: {
            type: 'string',
            minLength: 1,
            description: 'Symbol of the ship that executed the siphon.'
        },
        yield: {
            $ref: '#/components/schemas/SiphonYield'
        }
    },
    required: [
        'shipSymbol',
        'yield'
    ],
    description: 'Siphon details.'
} as const;

export const SiphonYieldSchema = {
    type: 'object',
    properties: {
        symbol: {
            $ref: '#/components/schemas/TradeSymbol'
        },
        units: {
            type: 'integer',
            description: 'The number of units siphoned that were placed into the ship\'s cargo hold.'
        }
    },
    required: [
        'symbol',
        'units'
    ],
    description: 'A yield from the siphon operation.'
} as const;

export const ShipModificationTransactionSchema = {
    type: 'object',
    properties: {
        waypointSymbol: {
            type: 'string',
            description: 'The symbol of the waypoint where the transaction took place.'
        },
        shipSymbol: {
            type: 'string',
            description: 'The symbol of the ship that made the transaction.'
        },
        tradeSymbol: {
            type: 'string',
            description: 'The symbol of the trade good.'
        },
        totalPrice: {
            type: 'integer',
            minimum: 0,
            description: 'The total price of the transaction.'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            description: 'The timestamp of the transaction.'
        }
    },
    required: [
        'waypointSymbol',
        'shipSymbol',
        'tradeSymbol',
        'totalPrice',
        'timestamp'
    ],
    description: 'Result of a transaction for a ship modification, such as installing a mount or a module.'
} as const;
