// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.spacetraders.io/v2' | (string & {});
};

/**
 * Faction details.
 */
export type Faction = {
    symbol: FactionSymbol;
    /**
     * Name of the faction.
     */
    name: string;
    /**
     * Description of the faction.
     */
    description: string;
    /**
     * The waypoint in which the faction's HQ is located in.
     */
    headquarters?: string;
    /**
     * List of traits that define this faction.
     */
    traits: Array<FactionTrait>;
    /**
     * Whether or not the faction is currently recruiting new agents.
     */
    isRecruiting: boolean;
};

/**
 * The symbol of the faction.
 */
export const FactionSymbol = {
    COSMIC: 'COSMIC',
    VOID: 'VOID',
    GALACTIC: 'GALACTIC',
    QUANTUM: 'QUANTUM',
    DOMINION: 'DOMINION',
    ASTRO: 'ASTRO',
    CORSAIRS: 'CORSAIRS',
    OBSIDIAN: 'OBSIDIAN',
    AEGIS: 'AEGIS',
    UNITED: 'UNITED',
    SOLITARY: 'SOLITARY',
    COBALT: 'COBALT',
    OMEGA: 'OMEGA',
    ECHO: 'ECHO',
    LORDS: 'LORDS',
    CULT: 'CULT',
    ANCIENTS: 'ANCIENTS',
    SHADOW: 'SHADOW',
    ETHEREAL: 'ETHEREAL'
} as const;

/**
 * The symbol of the faction.
 */
export type FactionSymbol = typeof FactionSymbol[keyof typeof FactionSymbol];

export type FactionTrait = {
    symbol: FactionTraitSymbol;
    /**
     * The name of the trait.
     */
    name: string;
    /**
     * A description of the trait.
     */
    description: string;
};

/**
 * The unique identifier of the trait.
 */
export const FactionTraitSymbol = {
    BUREAUCRATIC: 'BUREAUCRATIC',
    SECRETIVE: 'SECRETIVE',
    CAPITALISTIC: 'CAPITALISTIC',
    INDUSTRIOUS: 'INDUSTRIOUS',
    PEACEFUL: 'PEACEFUL',
    DISTRUSTFUL: 'DISTRUSTFUL',
    WELCOMING: 'WELCOMING',
    SMUGGLERS: 'SMUGGLERS',
    SCAVENGERS: 'SCAVENGERS',
    REBELLIOUS: 'REBELLIOUS',
    EXILES: 'EXILES',
    PIRATES: 'PIRATES',
    RAIDERS: 'RAIDERS',
    CLAN: 'CLAN',
    GUILD: 'GUILD',
    DOMINION: 'DOMINION',
    FRINGE: 'FRINGE',
    FORSAKEN: 'FORSAKEN',
    ISOLATED: 'ISOLATED',
    LOCALIZED: 'LOCALIZED',
    ESTABLISHED: 'ESTABLISHED',
    NOTABLE: 'NOTABLE',
    DOMINANT: 'DOMINANT',
    INESCAPABLE: 'INESCAPABLE',
    INNOVATIVE: 'INNOVATIVE',
    BOLD: 'BOLD',
    VISIONARY: 'VISIONARY',
    CURIOUS: 'CURIOUS',
    DARING: 'DARING',
    EXPLORATORY: 'EXPLORATORY',
    RESOURCEFUL: 'RESOURCEFUL',
    FLEXIBLE: 'FLEXIBLE',
    COOPERATIVE: 'COOPERATIVE',
    UNITED: 'UNITED',
    STRATEGIC: 'STRATEGIC',
    INTELLIGENT: 'INTELLIGENT',
    RESEARCH_FOCUSED: 'RESEARCH_FOCUSED',
    COLLABORATIVE: 'COLLABORATIVE',
    PROGRESSIVE: 'PROGRESSIVE',
    MILITARISTIC: 'MILITARISTIC',
    TECHNOLOGICALLY_ADVANCED: 'TECHNOLOGICALLY_ADVANCED',
    AGGRESSIVE: 'AGGRESSIVE',
    IMPERIALISTIC: 'IMPERIALISTIC',
    TREASURE_HUNTERS: 'TREASURE_HUNTERS',
    DEXTEROUS: 'DEXTEROUS',
    UNPREDICTABLE: 'UNPREDICTABLE',
    BRUTAL: 'BRUTAL',
    FLEETING: 'FLEETING',
    ADAPTABLE: 'ADAPTABLE',
    SELF_SUFFICIENT: 'SELF_SUFFICIENT',
    DEFENSIVE: 'DEFENSIVE',
    PROUD: 'PROUD',
    DIVERSE: 'DIVERSE',
    INDEPENDENT: 'INDEPENDENT',
    SELF_INTERESTED: 'SELF_INTERESTED',
    FRAGMENTED: 'FRAGMENTED',
    COMMERCIAL: 'COMMERCIAL',
    FREE_MARKETS: 'FREE_MARKETS',
    ENTREPRENEURIAL: 'ENTREPRENEURIAL'
} as const;

/**
 * The unique identifier of the trait.
 */
export type FactionTraitSymbol = typeof FactionTraitSymbol[keyof typeof FactionTraitSymbol];

/**
 * Meta details for pagination.
 */
export type Meta = {
    /**
     * Shows the total amount of items of this kind that exist.
     */
    total: number;
    /**
     * A page denotes an amount of items, offset from the first item. Each page holds an amount of items equal to the `limit`.
     */
    page: number;
    /**
     * The amount of items in each page. Limits how many items can be fetched at once.
     */
    limit: number;
};

/**
 * Public agent details.
 */
export type PublicAgent = {
    /**
     * Symbol of the agent.
     */
    symbol: string;
    /**
     * The headquarters of the agent.
     */
    headquarters: string;
    /**
     * The number of credits the agent has available. Credits can be negative if funds have been overdrawn.
     */
    credits: bigint;
    /**
     * The faction the agent started with.
     */
    startingFaction: string;
    /**
     * How many ships are owned by the agent.
     */
    shipCount: number;
};

/**
 * System details.
 */
export type System = {
    /**
     * The constellation that the system is part of.
     */
    constellation?: string;
    /**
     * The symbol of the system.
     */
    symbol: string;
    /**
     * The symbol of the sector.
     */
    sectorSymbol: string;
    type: SystemType;
    /**
     * Relative position of the system in the sector in the x axis.
     */
    x: number;
    /**
     * Relative position of the system in the sector in the y axis.
     */
    y: number;
    /**
     * Waypoints in this system.
     */
    waypoints: Array<SystemWaypoint>;
    /**
     * Factions that control this system.
     */
    factions: Array<SystemFaction>;
    /**
     * The name of the system.
     */
    name?: string;
};

/**
 * The type of system.
 */
export const SystemType = {
    NEUTRON_STAR: 'NEUTRON_STAR',
    RED_STAR: 'RED_STAR',
    ORANGE_STAR: 'ORANGE_STAR',
    BLUE_STAR: 'BLUE_STAR',
    YOUNG_STAR: 'YOUNG_STAR',
    WHITE_DWARF: 'WHITE_DWARF',
    BLACK_HOLE: 'BLACK_HOLE',
    HYPERGIANT: 'HYPERGIANT',
    NEBULA: 'NEBULA',
    UNSTABLE: 'UNSTABLE'
} as const;

/**
 * The type of system.
 */
export type SystemType = typeof SystemType[keyof typeof SystemType];

/**
 * Waypoint details.
 */
export type SystemWaypoint = {
    symbol: WaypointSymbol;
    type: WaypointType;
    /**
     * Relative position of the waypoint on the system's x axis. This is not an absolute position in the universe.
     */
    x: number;
    /**
     * Relative position of the waypoint on the system's y axis. This is not an absolute position in the universe.
     */
    y: number;
    /**
     * Waypoints that orbit this waypoint.
     */
    orbitals: Array<WaypointOrbital>;
    /**
     * The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.
     */
    orbits?: string;
};

/**
 * The symbol of the waypoint.
 */
export type WaypointSymbol = string;

/**
 * The type of waypoint.
 */
export const WaypointType = {
    PLANET: 'PLANET',
    GAS_GIANT: 'GAS_GIANT',
    MOON: 'MOON',
    ORBITAL_STATION: 'ORBITAL_STATION',
    JUMP_GATE: 'JUMP_GATE',
    ASTEROID_FIELD: 'ASTEROID_FIELD',
    ASTEROID: 'ASTEROID',
    ENGINEERED_ASTEROID: 'ENGINEERED_ASTEROID',
    ASTEROID_BASE: 'ASTEROID_BASE',
    NEBULA: 'NEBULA',
    DEBRIS_FIELD: 'DEBRIS_FIELD',
    GRAVITY_WELL: 'GRAVITY_WELL',
    ARTIFICIAL_GRAVITY_WELL: 'ARTIFICIAL_GRAVITY_WELL',
    FUEL_STATION: 'FUEL_STATION'
} as const;

/**
 * The type of waypoint.
 */
export type WaypointType = typeof WaypointType[keyof typeof WaypointType];

/**
 * An orbital is another waypoint that orbits a parent waypoint.
 */
export type WaypointOrbital = {
    /**
     * The symbol of the orbiting waypoint.
     */
    symbol: string;
};

export type SystemFaction = {
    symbol: FactionSymbol;
};

/**
 * A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
 */
export type Waypoint = {
    symbol: WaypointSymbol;
    type: WaypointType;
    systemSymbol: SystemSymbol;
    /**
     * Relative position of the waypoint on the system's x axis. This is not an absolute position in the universe.
     */
    x: number;
    /**
     * Relative position of the waypoint on the system's y axis. This is not an absolute position in the universe.
     */
    y: number;
    /**
     * Waypoints that orbit this waypoint.
     */
    orbitals: Array<WaypointOrbital>;
    /**
     * The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.
     */
    orbits?: string;
    faction?: WaypointFaction;
    /**
     * The traits of the waypoint.
     */
    traits: Array<WaypointTrait>;
    /**
     * The modifiers of the waypoint.
     */
    modifiers?: Array<WaypointModifier>;
    chart?: Chart;
    /**
     * True if the waypoint is under construction.
     */
    isUnderConstruction: boolean;
};

/**
 * The symbol of the system.
 */
export type SystemSymbol = string;

/**
 * The faction that controls the waypoint.
 */
export type WaypointFaction = {
    symbol: FactionSymbol;
};

export type WaypointTrait = {
    symbol: WaypointTraitSymbol;
    /**
     * The name of the trait.
     */
    name: string;
    /**
     * A description of the trait.
     */
    description: string;
};

/**
 * The unique identifier of the trait.
 */
export const WaypointTraitSymbol = {
    UNCHARTED: 'UNCHARTED',
    UNDER_CONSTRUCTION: 'UNDER_CONSTRUCTION',
    MARKETPLACE: 'MARKETPLACE',
    SHIPYARD: 'SHIPYARD',
    OUTPOST: 'OUTPOST',
    SCATTERED_SETTLEMENTS: 'SCATTERED_SETTLEMENTS',
    SPRAWLING_CITIES: 'SPRAWLING_CITIES',
    MEGA_STRUCTURES: 'MEGA_STRUCTURES',
    PIRATE_BASE: 'PIRATE_BASE',
    OVERCROWDED: 'OVERCROWDED',
    HIGH_TECH: 'HIGH_TECH',
    CORRUPT: 'CORRUPT',
    BUREAUCRATIC: 'BUREAUCRATIC',
    TRADING_HUB: 'TRADING_HUB',
    INDUSTRIAL: 'INDUSTRIAL',
    BLACK_MARKET: 'BLACK_MARKET',
    RESEARCH_FACILITY: 'RESEARCH_FACILITY',
    MILITARY_BASE: 'MILITARY_BASE',
    SURVEILLANCE_OUTPOST: 'SURVEILLANCE_OUTPOST',
    EXPLORATION_OUTPOST: 'EXPLORATION_OUTPOST',
    MINERAL_DEPOSITS: 'MINERAL_DEPOSITS',
    COMMON_METAL_DEPOSITS: 'COMMON_METAL_DEPOSITS',
    PRECIOUS_METAL_DEPOSITS: 'PRECIOUS_METAL_DEPOSITS',
    RARE_METAL_DEPOSITS: 'RARE_METAL_DEPOSITS',
    METHANE_POOLS: 'METHANE_POOLS',
    ICE_CRYSTALS: 'ICE_CRYSTALS',
    EXPLOSIVE_GASES: 'EXPLOSIVE_GASES',
    STRONG_MAGNETOSPHERE: 'STRONG_MAGNETOSPHERE',
    VIBRANT_AURORAS: 'VIBRANT_AURORAS',
    SALT_FLATS: 'SALT_FLATS',
    CANYONS: 'CANYONS',
    PERPETUAL_DAYLIGHT: 'PERPETUAL_DAYLIGHT',
    PERPETUAL_OVERCAST: 'PERPETUAL_OVERCAST',
    DRY_SEABEDS: 'DRY_SEABEDS',
    MAGMA_SEAS: 'MAGMA_SEAS',
    SUPERVOLCANOES: 'SUPERVOLCANOES',
    ASH_CLOUDS: 'ASH_CLOUDS',
    VAST_RUINS: 'VAST_RUINS',
    MUTATED_FLORA: 'MUTATED_FLORA',
    TERRAFORMED: 'TERRAFORMED',
    EXTREME_TEMPERATURES: 'EXTREME_TEMPERATURES',
    EXTREME_PRESSURE: 'EXTREME_PRESSURE',
    DIVERSE_LIFE: 'DIVERSE_LIFE',
    SCARCE_LIFE: 'SCARCE_LIFE',
    FOSSILS: 'FOSSILS',
    WEAK_GRAVITY: 'WEAK_GRAVITY',
    STRONG_GRAVITY: 'STRONG_GRAVITY',
    CRUSHING_GRAVITY: 'CRUSHING_GRAVITY',
    TOXIC_ATMOSPHERE: 'TOXIC_ATMOSPHERE',
    CORROSIVE_ATMOSPHERE: 'CORROSIVE_ATMOSPHERE',
    BREATHABLE_ATMOSPHERE: 'BREATHABLE_ATMOSPHERE',
    THIN_ATMOSPHERE: 'THIN_ATMOSPHERE',
    JOVIAN: 'JOVIAN',
    ROCKY: 'ROCKY',
    VOLCANIC: 'VOLCANIC',
    FROZEN: 'FROZEN',
    SWAMP: 'SWAMP',
    BARREN: 'BARREN',
    TEMPERATE: 'TEMPERATE',
    JUNGLE: 'JUNGLE',
    OCEAN: 'OCEAN',
    RADIOACTIVE: 'RADIOACTIVE',
    MICRO_GRAVITY_ANOMALIES: 'MICRO_GRAVITY_ANOMALIES',
    DEBRIS_CLUSTER: 'DEBRIS_CLUSTER',
    DEEP_CRATERS: 'DEEP_CRATERS',
    SHALLOW_CRATERS: 'SHALLOW_CRATERS',
    UNSTABLE_COMPOSITION: 'UNSTABLE_COMPOSITION',
    HOLLOWED_INTERIOR: 'HOLLOWED_INTERIOR',
    STRIPPED: 'STRIPPED'
} as const;

/**
 * The unique identifier of the trait.
 */
export type WaypointTraitSymbol = typeof WaypointTraitSymbol[keyof typeof WaypointTraitSymbol];

export type WaypointModifier = {
    symbol: WaypointModifierSymbol;
    /**
     * The name of the trait.
     */
    name: string;
    /**
     * A description of the trait.
     */
    description: string;
};

/**
 * Waypoint Modifier Symbol
 *
 * The unique identifier of the modifier.
 */
export const WaypointModifierSymbol = {
    STRIPPED: 'STRIPPED',
    UNSTABLE: 'UNSTABLE',
    RADIATION_LEAK: 'RADIATION_LEAK',
    CRITICAL_LIMIT: 'CRITICAL_LIMIT',
    CIVIL_UNREST: 'CIVIL_UNREST'
} as const;

/**
 * Waypoint Modifier Symbol
 *
 * The unique identifier of the modifier.
 */
export type WaypointModifierSymbol = typeof WaypointModifierSymbol[keyof typeof WaypointModifierSymbol];

/**
 * The chart of a system or waypoint, which makes the location visible to other agents.
 */
export type Chart = {
    waypointSymbol: WaypointSymbol;
    /**
     * The agent that submitted the chart for this waypoint.
     */
    submittedBy: string;
    /**
     * The time the chart for this waypoint was submitted.
     */
    submittedOn: Date;
};

/**
 * The construction details of a waypoint.
 */
export type Construction = {
    /**
     * The symbol of the waypoint.
     */
    symbol: string;
    /**
     * The materials required to construct the waypoint.
     */
    materials: Array<ConstructionMaterial>;
    /**
     * Whether the waypoint has been constructed.
     */
    isComplete: boolean;
};

/**
 * The details of the required construction materials for a given waypoint under construction.
 */
export type ConstructionMaterial = {
    tradeSymbol: TradeSymbol;
    /**
     * The number of units required.
     */
    required: number;
    /**
     * The number of units fulfilled toward the required amount.
     */
    fulfilled: number;
};

/**
 * The good's symbol.
 */
export const TradeSymbol = {
    PRECIOUS_STONES: 'PRECIOUS_STONES',
    QUARTZ_SAND: 'QUARTZ_SAND',
    SILICON_CRYSTALS: 'SILICON_CRYSTALS',
    AMMONIA_ICE: 'AMMONIA_ICE',
    LIQUID_HYDROGEN: 'LIQUID_HYDROGEN',
    LIQUID_NITROGEN: 'LIQUID_NITROGEN',
    ICE_WATER: 'ICE_WATER',
    EXOTIC_MATTER: 'EXOTIC_MATTER',
    ADVANCED_CIRCUITRY: 'ADVANCED_CIRCUITRY',
    GRAVITON_EMITTERS: 'GRAVITON_EMITTERS',
    IRON: 'IRON',
    IRON_ORE: 'IRON_ORE',
    COPPER: 'COPPER',
    COPPER_ORE: 'COPPER_ORE',
    ALUMINUM: 'ALUMINUM',
    ALUMINUM_ORE: 'ALUMINUM_ORE',
    SILVER: 'SILVER',
    SILVER_ORE: 'SILVER_ORE',
    GOLD: 'GOLD',
    GOLD_ORE: 'GOLD_ORE',
    PLATINUM: 'PLATINUM',
    PLATINUM_ORE: 'PLATINUM_ORE',
    DIAMONDS: 'DIAMONDS',
    URANITE: 'URANITE',
    URANITE_ORE: 'URANITE_ORE',
    MERITIUM: 'MERITIUM',
    MERITIUM_ORE: 'MERITIUM_ORE',
    HYDROCARBON: 'HYDROCARBON',
    ANTIMATTER: 'ANTIMATTER',
    FAB_MATS: 'FAB_MATS',
    FERTILIZERS: 'FERTILIZERS',
    FABRICS: 'FABRICS',
    FOOD: 'FOOD',
    JEWELRY: 'JEWELRY',
    MACHINERY: 'MACHINERY',
    FIREARMS: 'FIREARMS',
    ASSAULT_RIFLES: 'ASSAULT_RIFLES',
    MILITARY_EQUIPMENT: 'MILITARY_EQUIPMENT',
    EXPLOSIVES: 'EXPLOSIVES',
    LAB_INSTRUMENTS: 'LAB_INSTRUMENTS',
    AMMUNITION: 'AMMUNITION',
    ELECTRONICS: 'ELECTRONICS',
    SHIP_PLATING: 'SHIP_PLATING',
    SHIP_PARTS: 'SHIP_PARTS',
    EQUIPMENT: 'EQUIPMENT',
    FUEL: 'FUEL',
    MEDICINE: 'MEDICINE',
    DRUGS: 'DRUGS',
    CLOTHING: 'CLOTHING',
    MICROPROCESSORS: 'MICROPROCESSORS',
    PLASTICS: 'PLASTICS',
    POLYNUCLEOTIDES: 'POLYNUCLEOTIDES',
    BIOCOMPOSITES: 'BIOCOMPOSITES',
    QUANTUM_STABILIZERS: 'QUANTUM_STABILIZERS',
    NANOBOTS: 'NANOBOTS',
    AI_MAINFRAMES: 'AI_MAINFRAMES',
    QUANTUM_DRIVES: 'QUANTUM_DRIVES',
    ROBOTIC_DRONES: 'ROBOTIC_DRONES',
    CYBER_IMPLANTS: 'CYBER_IMPLANTS',
    GENE_THERAPEUTICS: 'GENE_THERAPEUTICS',
    NEURAL_CHIPS: 'NEURAL_CHIPS',
    MOOD_REGULATORS: 'MOOD_REGULATORS',
    VIRAL_AGENTS: 'VIRAL_AGENTS',
    MICRO_FUSION_GENERATORS: 'MICRO_FUSION_GENERATORS',
    SUPERGRAINS: 'SUPERGRAINS',
    LASER_RIFLES: 'LASER_RIFLES',
    HOLOGRAPHICS: 'HOLOGRAPHICS',
    SHIP_SALVAGE: 'SHIP_SALVAGE',
    RELIC_TECH: 'RELIC_TECH',
    NOVEL_LIFEFORMS: 'NOVEL_LIFEFORMS',
    BOTANICAL_SPECIMENS: 'BOTANICAL_SPECIMENS',
    CULTURAL_ARTIFACTS: 'CULTURAL_ARTIFACTS',
    FRAME_PROBE: 'FRAME_PROBE',
    FRAME_DRONE: 'FRAME_DRONE',
    FRAME_INTERCEPTOR: 'FRAME_INTERCEPTOR',
    FRAME_RACER: 'FRAME_RACER',
    FRAME_FIGHTER: 'FRAME_FIGHTER',
    FRAME_FRIGATE: 'FRAME_FRIGATE',
    FRAME_SHUTTLE: 'FRAME_SHUTTLE',
    FRAME_EXPLORER: 'FRAME_EXPLORER',
    FRAME_MINER: 'FRAME_MINER',
    FRAME_LIGHT_FREIGHTER: 'FRAME_LIGHT_FREIGHTER',
    FRAME_HEAVY_FREIGHTER: 'FRAME_HEAVY_FREIGHTER',
    FRAME_TRANSPORT: 'FRAME_TRANSPORT',
    FRAME_DESTROYER: 'FRAME_DESTROYER',
    FRAME_CRUISER: 'FRAME_CRUISER',
    FRAME_CARRIER: 'FRAME_CARRIER',
    FRAME_BULK_FREIGHTER: 'FRAME_BULK_FREIGHTER',
    REACTOR_SOLAR_I: 'REACTOR_SOLAR_I',
    REACTOR_FUSION_I: 'REACTOR_FUSION_I',
    REACTOR_FISSION_I: 'REACTOR_FISSION_I',
    REACTOR_CHEMICAL_I: 'REACTOR_CHEMICAL_I',
    REACTOR_ANTIMATTER_I: 'REACTOR_ANTIMATTER_I',
    ENGINE_IMPULSE_DRIVE_I: 'ENGINE_IMPULSE_DRIVE_I',
    ENGINE_ION_DRIVE_I: 'ENGINE_ION_DRIVE_I',
    ENGINE_ION_DRIVE_II: 'ENGINE_ION_DRIVE_II',
    ENGINE_HYPER_DRIVE_I: 'ENGINE_HYPER_DRIVE_I',
    MODULE_MINERAL_PROCESSOR_I: 'MODULE_MINERAL_PROCESSOR_I',
    MODULE_GAS_PROCESSOR_I: 'MODULE_GAS_PROCESSOR_I',
    MODULE_CARGO_HOLD_I: 'MODULE_CARGO_HOLD_I',
    MODULE_CARGO_HOLD_II: 'MODULE_CARGO_HOLD_II',
    MODULE_CARGO_HOLD_III: 'MODULE_CARGO_HOLD_III',
    MODULE_CREW_QUARTERS_I: 'MODULE_CREW_QUARTERS_I',
    MODULE_ENVOY_QUARTERS_I: 'MODULE_ENVOY_QUARTERS_I',
    MODULE_PASSENGER_CABIN_I: 'MODULE_PASSENGER_CABIN_I',
    MODULE_MICRO_REFINERY_I: 'MODULE_MICRO_REFINERY_I',
    MODULE_SCIENCE_LAB_I: 'MODULE_SCIENCE_LAB_I',
    MODULE_JUMP_DRIVE_I: 'MODULE_JUMP_DRIVE_I',
    MODULE_JUMP_DRIVE_II: 'MODULE_JUMP_DRIVE_II',
    MODULE_JUMP_DRIVE_III: 'MODULE_JUMP_DRIVE_III',
    MODULE_WARP_DRIVE_I: 'MODULE_WARP_DRIVE_I',
    MODULE_WARP_DRIVE_II: 'MODULE_WARP_DRIVE_II',
    MODULE_WARP_DRIVE_III: 'MODULE_WARP_DRIVE_III',
    MODULE_SHIELD_GENERATOR_I: 'MODULE_SHIELD_GENERATOR_I',
    MODULE_SHIELD_GENERATOR_II: 'MODULE_SHIELD_GENERATOR_II',
    MODULE_ORE_REFINERY_I: 'MODULE_ORE_REFINERY_I',
    MODULE_FUEL_REFINERY_I: 'MODULE_FUEL_REFINERY_I',
    MOUNT_GAS_SIPHON_I: 'MOUNT_GAS_SIPHON_I',
    MOUNT_GAS_SIPHON_II: 'MOUNT_GAS_SIPHON_II',
    MOUNT_GAS_SIPHON_III: 'MOUNT_GAS_SIPHON_III',
    MOUNT_SURVEYOR_I: 'MOUNT_SURVEYOR_I',
    MOUNT_SURVEYOR_II: 'MOUNT_SURVEYOR_II',
    MOUNT_SURVEYOR_III: 'MOUNT_SURVEYOR_III',
    MOUNT_SENSOR_ARRAY_I: 'MOUNT_SENSOR_ARRAY_I',
    MOUNT_SENSOR_ARRAY_II: 'MOUNT_SENSOR_ARRAY_II',
    MOUNT_SENSOR_ARRAY_III: 'MOUNT_SENSOR_ARRAY_III',
    MOUNT_MINING_LASER_I: 'MOUNT_MINING_LASER_I',
    MOUNT_MINING_LASER_II: 'MOUNT_MINING_LASER_II',
    MOUNT_MINING_LASER_III: 'MOUNT_MINING_LASER_III',
    MOUNT_LASER_CANNON_I: 'MOUNT_LASER_CANNON_I',
    MOUNT_MISSILE_LAUNCHER_I: 'MOUNT_MISSILE_LAUNCHER_I',
    MOUNT_TURRET_I: 'MOUNT_TURRET_I',
    SHIP_PROBE: 'SHIP_PROBE',
    SHIP_MINING_DRONE: 'SHIP_MINING_DRONE',
    SHIP_SIPHON_DRONE: 'SHIP_SIPHON_DRONE',
    SHIP_INTERCEPTOR: 'SHIP_INTERCEPTOR',
    SHIP_LIGHT_HAULER: 'SHIP_LIGHT_HAULER',
    SHIP_COMMAND_FRIGATE: 'SHIP_COMMAND_FRIGATE',
    SHIP_EXPLORER: 'SHIP_EXPLORER',
    SHIP_HEAVY_FREIGHTER: 'SHIP_HEAVY_FREIGHTER',
    SHIP_LIGHT_SHUTTLE: 'SHIP_LIGHT_SHUTTLE',
    SHIP_ORE_HOUND: 'SHIP_ORE_HOUND',
    SHIP_REFINING_FREIGHTER: 'SHIP_REFINING_FREIGHTER',
    SHIP_SURVEYOR: 'SHIP_SURVEYOR',
    SHIP_BULK_FREIGHTER: 'SHIP_BULK_FREIGHTER'
} as const;

/**
 * The good's symbol.
 */
export type TradeSymbol = typeof TradeSymbol[keyof typeof TradeSymbol];

/**
 * Ship cargo details.
 */
export type ShipCargo = {
    /**
     * The max number of items that can be stored in the cargo hold.
     */
    capacity: number;
    /**
     * The number of items currently stored in the cargo hold.
     */
    units: number;
    /**
     * The items currently in the cargo hold.
     */
    inventory: Array<ShipCargoItem>;
};

/**
 * The type of cargo item and the number of units.
 */
export type ShipCargoItem = {
    symbol: TradeSymbol;
    /**
     * The name of the cargo item type.
     */
    name: string;
    /**
     * The description of the cargo item type.
     */
    description: string;
    /**
     * The number of units of the cargo item.
     */
    units: number;
};

/**
 * Market details.
 */
export type Market = {
    /**
     * The symbol of the market. The symbol is the same as the waypoint where the market is located.
     */
    symbol: string;
    /**
     * The list of goods that are exported from this market.
     */
    exports: Array<TradeGood>;
    /**
     * The list of goods that are sought as imports in this market.
     */
    imports: Array<TradeGood>;
    /**
     * The list of goods that are bought and sold between agents at this market.
     */
    exchange: Array<TradeGood>;
    /**
     * The list of recent transactions at this market. Visible only when a ship is present at the market.
     */
    transactions?: Array<MarketTransaction>;
    /**
     * The list of goods that are traded at this market. Visible only when a ship is present at the market.
     */
    tradeGoods?: Array<MarketTradeGood>;
};

/**
 * A good that can be traded for other goods or currency.
 */
export type TradeGood = {
    symbol: TradeSymbol;
    /**
     * The name of the good.
     */
    name: string;
    /**
     * The description of the good.
     */
    description: string;
};

/**
 * Result of a transaction with a market.
 */
export type MarketTransaction = {
    waypointSymbol: WaypointSymbol;
    /**
     * The symbol of the ship that made the transaction.
     */
    shipSymbol: string;
    /**
     * The symbol of the trade good.
     */
    tradeSymbol: string;
    /**
     * The type of transaction.
     */
    type: 'PURCHASE' | 'SELL';
    /**
     * The number of units of the transaction.
     */
    units: number;
    /**
     * The price per unit of the transaction.
     */
    pricePerUnit: number;
    /**
     * The total price of the transaction.
     */
    totalPrice: number;
    /**
     * The timestamp of the transaction.
     */
    timestamp: Date;
};

export type MarketTradeGood = {
    symbol: TradeSymbol;
    /**
     * The type of trade good (export, import, or exchange).
     */
    type: 'EXPORT' | 'IMPORT' | 'EXCHANGE';
    /**
     * This is the maximum number of units that can be purchased or sold at this market in a single trade for this good. Trade volume also gives an indication of price volatility. A market with a low trade volume will have large price swings, while high trade volume will be more resilient to price changes.
     */
    tradeVolume: number;
    supply: SupplyLevel;
    activity?: ActivityLevel;
    /**
     * The price at which this good can be purchased from the market.
     */
    purchasePrice: number;
    /**
     * The price at which this good can be sold to the market.
     */
    sellPrice: number;
};

/**
 * The supply level of a trade good.
 */
export const SupplyLevel = {
    SCARCE: 'SCARCE',
    LIMITED: 'LIMITED',
    MODERATE: 'MODERATE',
    HIGH: 'HIGH',
    ABUNDANT: 'ABUNDANT'
} as const;

/**
 * The supply level of a trade good.
 */
export type SupplyLevel = typeof SupplyLevel[keyof typeof SupplyLevel];

/**
 * The activity level of a trade good. If the good is an import, this represents how strong consumption is. If the good is an export, this represents how strong the production is for the good. When activity is strong, consumption or production is near maximum capacity. When activity is weak, consumption or production is near minimum capacity.
 */
export const ActivityLevel = {
    WEAK: 'WEAK',
    GROWING: 'GROWING',
    STRONG: 'STRONG',
    RESTRICTED: 'RESTRICTED'
} as const;

/**
 * The activity level of a trade good. If the good is an import, this represents how strong consumption is. If the good is an export, this represents how strong the production is for the good. When activity is strong, consumption or production is near maximum capacity. When activity is weak, consumption or production is near minimum capacity.
 */
export type ActivityLevel = typeof ActivityLevel[keyof typeof ActivityLevel];

/**
 * Details of a jump gate waypoint.
 */
export type JumpGate = {
    symbol: WaypointSymbol;
    /**
     * All the gates that are connected to this waypoint.
     */
    connections: Array<string>;
};

/**
 * Shipyard details.
 */
export type Shipyard = {
    /**
     * The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.
     */
    symbol: string;
    /**
     * The list of ship types available for purchase at this shipyard.
     */
    shipTypes: Array<{
        type: ShipType;
    }>;
    /**
     * The list of recent transactions at this shipyard.
     */
    transactions?: Array<ShipyardTransaction>;
    /**
     * The ships that are currently available for purchase at the shipyard.
     */
    ships?: Array<ShipyardShip>;
    /**
     * The fee to modify a ship at this shipyard. This includes installing or removing modules and mounts on a ship. In the case of mounts, the fee is a flat rate per mount. In the case of modules, the fee is per slot the module occupies.
     */
    modificationsFee: number;
};

/**
 * Type of ship
 */
export const ShipType = {
    SHIP_PROBE: 'SHIP_PROBE',
    SHIP_MINING_DRONE: 'SHIP_MINING_DRONE',
    SHIP_SIPHON_DRONE: 'SHIP_SIPHON_DRONE',
    SHIP_INTERCEPTOR: 'SHIP_INTERCEPTOR',
    SHIP_LIGHT_HAULER: 'SHIP_LIGHT_HAULER',
    SHIP_COMMAND_FRIGATE: 'SHIP_COMMAND_FRIGATE',
    SHIP_EXPLORER: 'SHIP_EXPLORER',
    SHIP_HEAVY_FREIGHTER: 'SHIP_HEAVY_FREIGHTER',
    SHIP_LIGHT_SHUTTLE: 'SHIP_LIGHT_SHUTTLE',
    SHIP_ORE_HOUND: 'SHIP_ORE_HOUND',
    SHIP_REFINING_FREIGHTER: 'SHIP_REFINING_FREIGHTER',
    SHIP_SURVEYOR: 'SHIP_SURVEYOR',
    SHIP_BULK_FREIGHTER: 'SHIP_BULK_FREIGHTER'
} as const;

/**
 * Type of ship
 */
export type ShipType = typeof ShipType[keyof typeof ShipType];

/**
 * Results of a transaction with a shipyard.
 */
export type ShipyardTransaction = {
    waypointSymbol: WaypointSymbol;
    /**
     * The symbol of the ship type (e.g. SHIP_MINING_DRONE) that was the subject of the transaction. Contrary to what the name implies, this is NOT the symbol of the ship that was purchased.
     *
     * @deprecated
     */
    shipSymbol: string;
    /**
     * The symbol of the ship type (e.g. SHIP_MINING_DRONE) that was the subject of the transaction.
     */
    shipType: string;
    /**
     * The price of the transaction.
     */
    price: number;
    /**
     * The symbol of the agent that made the transaction.
     */
    agentSymbol: string;
    /**
     * The timestamp of the transaction.
     */
    timestamp: Date;
};

/**
 * Ship details available at a shipyard.
 */
export type ShipyardShip = {
    type: ShipType;
    /**
     * Name of the ship.
     */
    name: string;
    /**
     * Description of the ship.
     */
    description: string;
    activity?: ActivityLevel;
    supply: SupplyLevel;
    /**
     * The purchase price of the ship.
     */
    purchasePrice: number;
    frame: ShipFrame;
    reactor: ShipReactor;
    engine: ShipEngine;
    /**
     * Modules installed in this ship.
     */
    modules: Array<ShipModule>;
    /**
     * Mounts installed in this ship.
     */
    mounts: Array<ShipMount>;
    crew: {
        /**
         * The minimum number of crew members required to maintain the ship.
         */
        required: number;
        /**
         * The maximum number of crew members the ship can support.
         */
        capacity: number;
    };
};

/**
 * The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
 */
export type ShipFrame = {
    /**
     * Symbol of the frame.
     */
    symbol: 'FRAME_PROBE' | 'FRAME_DRONE' | 'FRAME_INTERCEPTOR' | 'FRAME_RACER' | 'FRAME_FIGHTER' | 'FRAME_FRIGATE' | 'FRAME_SHUTTLE' | 'FRAME_EXPLORER' | 'FRAME_MINER' | 'FRAME_LIGHT_FREIGHTER' | 'FRAME_HEAVY_FREIGHTER' | 'FRAME_TRANSPORT' | 'FRAME_DESTROYER' | 'FRAME_CRUISER' | 'FRAME_CARRIER' | 'FRAME_BULK_FREIGHTER';
    /**
     * Name of the frame.
     */
    name: string;
    condition: ShipComponentCondition;
    integrity: ShipComponentIntegrity;
    /**
     * Description of the frame.
     */
    description: string;
    /**
     * The amount of slots that can be dedicated to modules installed in the ship. Each installed module take up a number of slots, and once there are no more slots, no new modules can be installed.
     */
    moduleSlots: number;
    /**
     * The amount of slots that can be dedicated to mounts installed in the ship. Each installed mount takes up a number of points, and once there are no more points remaining, no new mounts can be installed.
     */
    mountingPoints: number;
    /**
     * The maximum amount of fuel that can be stored in this ship. When refueling, the ship will be refueled to this amount.
     */
    fuelCapacity: number;
    requirements: ShipRequirements;
    quality: ShipComponentQuality;
};

/**
 * The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.
 */
export type ShipComponentCondition = number;

/**
 * The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.
 */
export type ShipComponentIntegrity = number;

/**
 * The requirements for installation on a ship
 */
export type ShipRequirements = {
    /**
     * The amount of power required from the reactor.
     */
    power?: number;
    /**
     * The number of crew required for operation.
     */
    crew?: number;
    /**
     * The number of module slots required for installation.
     */
    slots?: number;
};

/**
 * The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.
 */
export type ShipComponentQuality = number;

/**
 * The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
 */
export type ShipReactor = {
    /**
     * Symbol of the reactor.
     */
    symbol: 'REACTOR_SOLAR_I' | 'REACTOR_FUSION_I' | 'REACTOR_FISSION_I' | 'REACTOR_CHEMICAL_I' | 'REACTOR_ANTIMATTER_I';
    /**
     * Name of the reactor.
     */
    name: string;
    condition: ShipComponentCondition;
    integrity: ShipComponentIntegrity;
    /**
     * Description of the reactor.
     */
    description: string;
    /**
     * The amount of power provided by this reactor. The more power a reactor provides to the ship, the lower the cooldown it gets when using a module or mount that taxes the ship's power.
     */
    powerOutput: number;
    requirements: ShipRequirements;
    quality: ShipComponentQuality;
};

/**
 * The engine determines how quickly a ship travels between waypoints.
 */
export type ShipEngine = {
    /**
     * The symbol of the engine.
     */
    symbol: 'ENGINE_IMPULSE_DRIVE_I' | 'ENGINE_ION_DRIVE_I' | 'ENGINE_ION_DRIVE_II' | 'ENGINE_HYPER_DRIVE_I';
    /**
     * The name of the engine.
     */
    name: string;
    condition: ShipComponentCondition;
    integrity: ShipComponentIntegrity;
    /**
     * The description of the engine.
     */
    description: string;
    /**
     * The speed stat of this engine. The higher the speed, the faster a ship can travel from one point to another. Reduces the time of arrival when navigating the ship.
     */
    speed: number;
    requirements: ShipRequirements;
    quality: ShipComponentQuality;
};

/**
 * A module can be installed in a ship and provides a set of capabilities such as storage space or quarters for crew. Module installations are permanent.
 */
export type ShipModule = {
    /**
     * The symbol of the module.
     */
    symbol: 'MODULE_MINERAL_PROCESSOR_I' | 'MODULE_GAS_PROCESSOR_I' | 'MODULE_CARGO_HOLD_I' | 'MODULE_CARGO_HOLD_II' | 'MODULE_CARGO_HOLD_III' | 'MODULE_CREW_QUARTERS_I' | 'MODULE_ENVOY_QUARTERS_I' | 'MODULE_PASSENGER_CABIN_I' | 'MODULE_MICRO_REFINERY_I' | 'MODULE_ORE_REFINERY_I' | 'MODULE_FUEL_REFINERY_I' | 'MODULE_SCIENCE_LAB_I' | 'MODULE_JUMP_DRIVE_I' | 'MODULE_JUMP_DRIVE_II' | 'MODULE_JUMP_DRIVE_III' | 'MODULE_WARP_DRIVE_I' | 'MODULE_WARP_DRIVE_II' | 'MODULE_WARP_DRIVE_III' | 'MODULE_SHIELD_GENERATOR_I' | 'MODULE_SHIELD_GENERATOR_II';
    /**
     * Name of this module.
     */
    name: string;
    /**
     * Description of this module.
     */
    description: string;
    /**
     * Modules that provide capacity, such as cargo hold or crew quarters will show this value to denote how much of a bonus the module grants.
     */
    capacity?: number;
    /**
     * Modules that have a range will such as a sensor array show this value to denote how far can the module reach with its capabilities.
     */
    range?: number;
    requirements: ShipRequirements;
};

/**
 * A mount is installed on the exterier of a ship.
 */
export type ShipMount = {
    /**
     * Symbol of this mount.
     */
    symbol: 'MOUNT_GAS_SIPHON_I' | 'MOUNT_GAS_SIPHON_II' | 'MOUNT_GAS_SIPHON_III' | 'MOUNT_SURVEYOR_I' | 'MOUNT_SURVEYOR_II' | 'MOUNT_SURVEYOR_III' | 'MOUNT_SENSOR_ARRAY_I' | 'MOUNT_SENSOR_ARRAY_II' | 'MOUNT_SENSOR_ARRAY_III' | 'MOUNT_MINING_LASER_I' | 'MOUNT_MINING_LASER_II' | 'MOUNT_MINING_LASER_III' | 'MOUNT_LASER_CANNON_I' | 'MOUNT_MISSILE_LAUNCHER_I' | 'MOUNT_TURRET_I';
    /**
     * Name of this mount.
     */
    name: string;
    /**
     * Description of this mount.
     */
    description: string;
    /**
     * Mounts that have this value, such as mining lasers, denote how powerful this mount's capabilities are.
     */
    strength?: number;
    /**
     * Mounts that have this value denote what goods can be produced from using the mount.
     */
    deposits?: Array<'QUARTZ_SAND' | 'SILICON_CRYSTALS' | 'PRECIOUS_STONES' | 'ICE_WATER' | 'AMMONIA_ICE' | 'IRON_ORE' | 'COPPER_ORE' | 'SILVER_ORE' | 'ALUMINUM_ORE' | 'GOLD_ORE' | 'PLATINUM_ORE' | 'DIAMONDS' | 'URANITE_ORE' | 'MERITIUM_ORE'>;
    requirements: ShipRequirements;
};

/**
 * Contract details.
 */
export type Contract = {
    /**
     * ID of the contract.
     */
    id: string;
    /**
     * The symbol of the faction that this contract is for.
     */
    factionSymbol: string;
    /**
     * Type of contract.
     */
    type: 'PROCUREMENT' | 'TRANSPORT' | 'SHUTTLE';
    terms: ContractTerms;
    /**
     * Whether the contract has been accepted by the agent
     */
    accepted: boolean;
    /**
     * Whether the contract has been fulfilled
     */
    fulfilled: boolean;
    /**
     * Deprecated in favor of deadlineToAccept
     *
     * @deprecated
     */
    expiration: Date;
    /**
     * The time at which the contract is no longer available to be accepted
     */
    deadlineToAccept?: Date;
};

/**
 * The terms to fulfill the contract.
 */
export type ContractTerms = {
    /**
     * The deadline for the contract.
     */
    deadline: Date;
    payment: ContractPayment;
    /**
     * The cargo that needs to be delivered to fulfill the contract.
     */
    deliver?: Array<ContractDeliverGood>;
};

/**
 * Payments for the contract.
 */
export type ContractPayment = {
    /**
     * The amount of credits received up front for accepting the contract.
     */
    onAccepted: number;
    /**
     * The amount of credits received when the contract is fulfilled.
     */
    onFulfilled: number;
};

/**
 * The details of a delivery contract. Includes the type of good, units needed, and the destination.
 */
export type ContractDeliverGood = {
    /**
     * The symbol of the trade good to deliver.
     */
    tradeSymbol: string;
    /**
     * The destination where goods need to be delivered.
     */
    destinationSymbol: string;
    /**
     * The number of units that need to be delivered on this contract.
     */
    unitsRequired: number;
    /**
     * The number of units fulfilled on this contract.
     */
    unitsFulfilled: number;
};

/**
 * Agent details.
 */
export type Agent = {
    /**
     * Account ID that is tied to this agent. Only included on your own agent.
     */
    accountId: string;
    /**
     * Symbol of the agent.
     */
    symbol: string;
    /**
     * The headquarters of the agent.
     */
    headquarters: string;
    /**
     * The number of credits the agent has available. Credits can be negative if funds have been overdrawn.
     */
    credits: bigint;
    /**
     * The faction the agent started with.
     */
    startingFaction: string;
    /**
     * How many ships are owned by the agent.
     */
    shipCount: number;
};

/**
 * Agent event details.
 */
export type AgentEvent = {
    id: string;
    type: string;
    message: string;
    data?: unknown;
    createdAt: Date;
};

/**
 * Ship details.
 */
export type Ship = {
    /**
     * The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]-[HEX_ID]`
     */
    symbol: string;
    registration: ShipRegistration;
    nav: ShipNav;
    crew: ShipCrew;
    frame: ShipFrame;
    reactor: ShipReactor;
    engine: ShipEngine;
    /**
     * Modules installed in this ship.
     */
    modules: Array<ShipModule>;
    /**
     * Mounts installed in this ship.
     */
    mounts: Array<ShipMount>;
    cargo: ShipCargo;
    fuel: ShipFuel;
    cooldown: Cooldown;
};

/**
 * The public registration information of the ship
 */
export type ShipRegistration = {
    /**
     * The agent's registered name of the ship
     */
    name: string;
    /**
     * The symbol of the faction the ship is registered with
     */
    factionSymbol: string;
    role: ShipRole;
};

/**
 * The registered role of the ship
 */
export const ShipRole = {
    FABRICATOR: 'FABRICATOR',
    HARVESTER: 'HARVESTER',
    HAULER: 'HAULER',
    INTERCEPTOR: 'INTERCEPTOR',
    EXCAVATOR: 'EXCAVATOR',
    TRANSPORT: 'TRANSPORT',
    REPAIR: 'REPAIR',
    SURVEYOR: 'SURVEYOR',
    COMMAND: 'COMMAND',
    CARRIER: 'CARRIER',
    PATROL: 'PATROL',
    SATELLITE: 'SATELLITE',
    EXPLORER: 'EXPLORER',
    REFINERY: 'REFINERY'
} as const;

/**
 * The registered role of the ship
 */
export type ShipRole = typeof ShipRole[keyof typeof ShipRole];

/**
 * The navigation information of the ship.
 */
export type ShipNav = {
    systemSymbol: SystemSymbol;
    waypointSymbol: WaypointSymbol;
    route: ShipNavRoute;
    status: ShipNavStatus;
    flightMode: ShipNavFlightMode;
};

/**
 * The routing information for the ship's most recent transit or current location.
 */
export type ShipNavRoute = {
    destination: ShipNavRouteWaypoint;
    origin: ShipNavRouteWaypoint;
    /**
     * The date time of the ship's departure.
     */
    departureTime: Date;
    /**
     * The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival.
     */
    arrival: Date;
};

/**
 * The destination or departure of a ships nav route.
 */
export type ShipNavRouteWaypoint = {
    /**
     * The symbol of the waypoint.
     */
    symbol: string;
    type: WaypointType;
    systemSymbol: SystemSymbol;
    /**
     * Position in the universe in the x axis.
     */
    x: number;
    /**
     * Position in the universe in the y axis.
     */
    y: number;
};

/**
 * The current status of the ship
 */
export const ShipNavStatus = {
    IN_TRANSIT: 'IN_TRANSIT',
    IN_ORBIT: 'IN_ORBIT',
    DOCKED: 'DOCKED'
} as const;

/**
 * The current status of the ship
 */
export type ShipNavStatus = typeof ShipNavStatus[keyof typeof ShipNavStatus];

/**
 * The ship's set speed when traveling between waypoints or systems.
 */
export const ShipNavFlightMode = {
    DRIFT: 'DRIFT',
    STEALTH: 'STEALTH',
    CRUISE: 'CRUISE',
    BURN: 'BURN'
} as const;

/**
 * The ship's set speed when traveling between waypoints or systems.
 */
export type ShipNavFlightMode = typeof ShipNavFlightMode[keyof typeof ShipNavFlightMode];

/**
 * The ship's crew service and maintain the ship's systems and equipment.
 */
export type ShipCrew = {
    /**
     * The current number of crew members on the ship.
     */
    current: number;
    /**
     * The minimum number of crew members required to maintain the ship.
     */
    required: number;
    /**
     * The maximum number of crew members the ship can support.
     */
    capacity: number;
    /**
     * The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.
     */
    rotation: 'STRICT' | 'RELAXED';
    /**
     * A rough measure of the crew's morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents.
     */
    morale: number;
    /**
     * The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint.
     */
    wages: number;
};

/**
 * Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
 */
export type ShipFuel = {
    /**
     * The current amount of fuel in the ship's tanks.
     */
    current: number;
    /**
     * The maximum amount of fuel the ship's tanks can hold.
     */
    capacity: number;
    /**
     * An object that only shows up when an action has consumed fuel in the process. Shows the fuel consumption data.
     */
    consumed?: {
        /**
         * The amount of fuel consumed by the most recent transit or action.
         */
        amount: number;
        /**
         * The time at which the fuel was consumed.
         */
        timestamp: Date;
    };
};

/**
 * A cooldown is a period of time in which a ship cannot perform certain actions.
 */
export type Cooldown = {
    /**
     * The symbol of the ship that is on cooldown
     */
    shipSymbol: string;
    /**
     * The total duration of the cooldown in seconds
     */
    totalSeconds: number;
    /**
     * The remaining duration of the cooldown in seconds
     */
    remainingSeconds: number;
    /**
     * The date and time when the cooldown expires in ISO 8601 format
     */
    expiration?: Date;
};

/**
 * Result of a chart transaction.
 */
export type ChartTransaction = {
    waypointSymbol: WaypointSymbol;
    /**
     * The symbol of the ship.
     */
    shipSymbol: string;
    /**
     * The total price of the transaction.
     */
    totalPrice: number;
    /**
     * The timestamp of the transaction.
     */
    timestamp: Date;
};

/**
 * Extraction details.
 */
export type Extraction = {
    /**
     * Symbol of the ship that executed the extraction.
     */
    shipSymbol: string;
    yield: ExtractionYield;
};

/**
 * A yield from the extraction operation.
 */
export type ExtractionYield = {
    symbol: TradeSymbol;
    /**
     * The number of units extracted that were placed into the ship's cargo hold.
     */
    units: number;
};

/**
 * An event that represents damage or wear to a ship's reactor, frame, or engine, reducing the condition of the ship.
 */
export type ShipConditionEvent = {
    /**
     * The symbol of the event that occurred.
     */
    symbol: 'REACTOR_OVERLOAD' | 'ENERGY_SPIKE_FROM_MINERAL' | 'SOLAR_FLARE_INTERFERENCE' | 'COOLANT_LEAK' | 'POWER_DISTRIBUTION_FLUCTUATION' | 'MAGNETIC_FIELD_DISRUPTION' | 'HULL_MICROMETEORITE_STRIKES' | 'STRUCTURAL_STRESS_FRACTURES' | 'CORROSIVE_MINERAL_CONTAMINATION' | 'THERMAL_EXPANSION_MISMATCH' | 'VIBRATION_DAMAGE_FROM_DRILLING' | 'ELECTROMAGNETIC_FIELD_INTERFERENCE' | 'IMPACT_WITH_EXTRACTED_DEBRIS' | 'FUEL_EFFICIENCY_DEGRADATION' | 'COOLANT_SYSTEM_AGEING' | 'DUST_MICROABRASIONS' | 'THRUSTER_NOZZLE_WEAR' | 'EXHAUST_PORT_CLOGGING' | 'BEARING_LUBRICATION_FADE' | 'SENSOR_CALIBRATION_DRIFT' | 'HULL_MICROMETEORITE_DAMAGE' | 'SPACE_DEBRIS_COLLISION' | 'THERMAL_STRESS' | 'VIBRATION_OVERLOAD' | 'PRESSURE_DIFFERENTIAL_STRESS' | 'ELECTROMAGNETIC_SURGE_EFFECTS' | 'ATMOSPHERIC_ENTRY_HEAT';
    component: 'FRAME' | 'REACTOR' | 'ENGINE';
    /**
     * The name of the event.
     */
    name: string;
    /**
     * A description of the event.
     */
    description: string;
};

/**
 * A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
 */
export type Survey = {
    /**
     * A unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.
     */
    signature: string;
    /**
     * The symbol of the waypoint that this survey is for.
     */
    symbol: string;
    /**
     * A list of deposits that can be found at this location. A ship will extract one of these deposits when using this survey in an extraction request. If multiple deposits of the same type are present, the chance of extracting that deposit is increased.
     */
    deposits: Array<SurveyDeposit>;
    /**
     * The date and time when the survey expires. After this date and time, the survey will no longer be available for extraction.
     */
    expiration: Date;
    size: SurveySize;
};

/**
 * A surveyed deposit of a mineral or resource available for extraction.
 */
export type SurveyDeposit = {
    /**
     * The symbol of the deposit.
     */
    symbol: TradeSymbol;
};

/**
 * The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
 */
export const SurveySize = {
    SMALL: 'SMALL',
    MODERATE: 'MODERATE',
    LARGE: 'LARGE'
} as const;

/**
 * The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
 */
export type SurveySize = typeof SurveySize[keyof typeof SurveySize];

/**
 * Details of a system was that scanned.
 */
export type ScannedSystem = {
    /**
     * Symbol of the system.
     */
    symbol: string;
    /**
     * Symbol of the system's sector.
     */
    sectorSymbol: string;
    type: SystemType;
    /**
     * Position in the universe in the x axis.
     */
    x: number;
    /**
     * Position in the universe in the y axis.
     */
    y: number;
    /**
     * The system's distance from the scanning ship.
     */
    distance: number;
};

/**
 * A waypoint that was scanned by a ship.
 */
export type ScannedWaypoint = {
    symbol: WaypointSymbol;
    type: WaypointType;
    systemSymbol: SystemSymbol;
    /**
     * Position in the universe in the x axis.
     */
    x: number;
    /**
     * Position in the universe in the y axis.
     */
    y: number;
    /**
     * List of waypoints that orbit this waypoint.
     */
    orbitals: Array<WaypointOrbital>;
    faction?: WaypointFaction;
    /**
     * The traits of the waypoint.
     */
    traits: Array<WaypointTrait>;
    chart?: Chart;
};

/**
 * The ship that was scanned. Details include information about the ship that could be detected by the scanner.
 */
export type ScannedShip = {
    /**
     * The globally unique identifier of the ship.
     */
    symbol: string;
    registration: ShipRegistration;
    nav: ShipNav;
    /**
     * The frame of the ship.
     */
    frame?: {
        /**
         * The symbol of the frame.
         */
        symbol: string;
    };
    /**
     * The reactor of the ship.
     */
    reactor?: {
        /**
         * The symbol of the reactor.
         */
        symbol: string;
    };
    /**
     * The engine of the ship.
     */
    engine: {
        /**
         * The symbol of the engine.
         */
        symbol: string;
    };
    /**
     * List of mounts installed in the ship.
     */
    mounts?: Array<{
        /**
         * The symbol of the mount.
         */
        symbol: string;
    }>;
};

/**
 * Result of a scrap transaction.
 */
export type ScrapTransaction = {
    waypointSymbol: WaypointSymbol;
    /**
     * The symbol of the ship.
     */
    shipSymbol: string;
    /**
     * The total price of the transaction.
     */
    totalPrice: number;
    /**
     * The timestamp of the transaction.
     */
    timestamp: Date;
};

/**
 * Result of a repair transaction.
 */
export type RepairTransaction = {
    waypointSymbol: WaypointSymbol;
    /**
     * The symbol of the ship.
     */
    shipSymbol: string;
    /**
     * The total price of the transaction.
     */
    totalPrice: number;
    /**
     * The timestamp of the transaction.
     */
    timestamp: Date;
};

/**
 * Siphon details.
 */
export type Siphon = {
    /**
     * Symbol of the ship that executed the siphon.
     */
    shipSymbol: string;
    yield: SiphonYield;
};

/**
 * A yield from the siphon operation.
 */
export type SiphonYield = {
    symbol: TradeSymbol;
    /**
     * The number of units siphoned that were placed into the ship's cargo hold.
     */
    units: number;
};

/**
 * Result of a transaction for a ship modification, such as installing a mount or a module.
 */
export type ShipModificationTransaction = {
    /**
     * The symbol of the waypoint where the transaction took place.
     */
    waypointSymbol: string;
    /**
     * The symbol of the ship that made the transaction.
     */
    shipSymbol: string;
    /**
     * The symbol of the trade good.
     */
    tradeSymbol: string;
    /**
     * The total price of the transaction.
     */
    totalPrice: number;
    /**
     * The timestamp of the transaction.
     */
    timestamp: Date;
};

export type GetFactionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * What entry offset to request
         */
        page?: number;
        /**
         * How many entries to return per page
         */
        limit?: number;
    };
    url: '/factions';
};

export type GetFactionsResponses = {
    /**
     * Successfully fetched factions.
     */
    200: {
        data: Array<Faction>;
        meta: Meta;
    };
};

export type GetFactionsResponse = GetFactionsResponses[keyof GetFactionsResponses];

export type GetFactionData = {
    body?: never;
    path: {
        /**
         * The faction symbol
         */
        factionSymbol: string;
    };
    query?: never;
    url: '/factions/{factionSymbol}';
};

export type GetFactionResponses = {
    /**
     * Default Response
     */
    200: {
        data: Faction;
    };
};

export type GetFactionResponse = GetFactionResponses[keyof GetFactionResponses];

export type GetAgentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * What entry offset to request
         */
        page?: number;
        /**
         * How many entries to return per page
         */
        limit?: number;
    };
    url: '/agents';
};

export type GetAgentsResponses = {
    /**
     * Successfully fetched agents details.
     */
    200: {
        data: Array<PublicAgent>;
        meta: Meta;
    };
};

export type GetAgentsResponse = GetAgentsResponses[keyof GetAgentsResponses];

export type GetAgentData = {
    body?: never;
    path: {
        /**
         * The agent symbol
         */
        agentSymbol: string;
    };
    query?: never;
    url: '/agents/{agentSymbol}';
};

export type GetAgentResponses = {
    /**
     * Default Response
     */
    200: {
        data: PublicAgent;
    };
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type GetSupplyChainData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/market/supply-chain';
};

export type GetSupplyChainResponses = {
    /**
     * Successfully retrieved the supply chain information
     */
    200: {
        data: {
            exportToImportMap: {
                [key: string]: Array<string>;
            };
        };
    };
};

export type GetSupplyChainResponse = GetSupplyChainResponses[keyof GetSupplyChainResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetStatusResponses = {
    /**
     * Fetched status successfully.
     */
    200: {
        /**
         * The current status of the game server.
         */
        status: string;
        /**
         * The current version of the API.
         */
        version: string;
        /**
         * The date when the game server was last reset.
         */
        resetDate: string;
        description: string;
        stats: {
            /**
             * Total number of accounts registered on the game server.
             */
            accounts?: number;
            /**
             * Number of registered agents in the game.
             */
            agents: number;
            /**
             * Total number of ships in the game.
             */
            ships: number;
            /**
             * Total number of systems in the game.
             */
            systems: number;
            /**
             * Total number of waypoints in the game.
             */
            waypoints: number;
        };
        health: {
            /**
             * The date/time when the market was last updated.
             */
            lastMarketUpdate?: string;
        };
        leaderboards: {
            /**
             * Top agents with the most credits.
             */
            mostCredits: Array<{
                /**
                 * Symbol of the agent.
                 */
                agentSymbol: string;
                /**
                 * Amount of credits.
                 */
                credits: bigint;
            }>;
            /**
             * Top agents with the most charted submitted.
             */
            mostSubmittedCharts: Array<{
                /**
                 * Symbol of the agent.
                 */
                agentSymbol: string;
                /**
                 * Amount of charts done by the agent.
                 */
                chartCount: number;
            }>;
        };
        serverResets: {
            /**
             * The date and time when the game server will reset.
             */
            next: string;
            /**
             * How often we intend to reset the game server.
             */
            frequency: string;
        };
        announcements: Array<{
            title: string;
            body: string;
        }>;
        links: Array<{
            name: string;
            url: string;
        }>;
    };
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetErrorCodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/error-codes';
};

export type GetErrorCodesResponses = {
    /**
     * Fetched error codes successfully.
     */
    200: {
        errorCodes: Array<{
            code: number;
            name: string;
        }>;
    };
};

export type GetErrorCodesResponse = GetErrorCodesResponses[keyof GetErrorCodesResponses];

export type GetSystemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * What entry offset to request
         */
        page?: number;
        /**
         * How many entries to return per page
         */
        limit?: number;
    };
    url: '/systems';
};

export type GetSystemsResponses = {
    /**
     * Successfully listed systems.
     */
    200: {
        data: Array<System>;
        meta: Meta;
    };
};

export type GetSystemsResponse = GetSystemsResponses[keyof GetSystemsResponses];

export type GetSystemData = {
    body?: never;
    path: {
        systemSymbol: string;
    };
    query?: never;
    url: '/systems/{systemSymbol}';
};

export type GetSystemResponses = {
    /**
     * Successfully fetched the system.
     */
    200: {
        data: System;
    };
};

export type GetSystemResponse = GetSystemResponses[keyof GetSystemResponses];

export type GetSystemWaypointsData = {
    body?: never;
    path: {
        systemSymbol: string;
    };
    query?: {
        /**
         * What entry offset to request
         */
        page?: number;
        /**
         * How many entries to return per page
         */
        limit?: number;
        /**
         * Filter waypoints by type.
         */
        type?: WaypointType;
        /**
         * Filter waypoints by one or more traits.
         */
        traits?: Array<WaypointTraitSymbol> | WaypointTraitSymbol;
    };
    url: '/systems/{systemSymbol}/waypoints';
};

export type GetSystemWaypointsResponses = {
    /**
     * Successfully listed waypoints.
     */
    200: {
        data: Array<Waypoint>;
        meta: Meta;
    };
};

export type GetSystemWaypointsResponse = GetSystemWaypointsResponses[keyof GetSystemWaypointsResponses];

export type GetWaypointData = {
    body?: never;
    path: {
        /**
         * The system symbol
         */
        systemSymbol: string;
        /**
         * The waypoint symbol
         */
        waypointSymbol: string;
    };
    query?: never;
    url: '/systems/{systemSymbol}/waypoints/{waypointSymbol}';
};

export type GetWaypointResponses = {
    /**
     * Successfully fetched waypoint details.
     */
    200: {
        data: Waypoint;
    };
};

export type GetWaypointResponse = GetWaypointResponses[keyof GetWaypointResponses];

export type GetConstructionData = {
    body?: never;
    path: {
        /**
         * The system symbol
         */
        systemSymbol: string;
        /**
         * The waypoint symbol
         */
        waypointSymbol: string;
    };
    query?: never;
    url: '/systems/{systemSymbol}/waypoints/{waypointSymbol}/construction';
};

export type GetConstructionResponses = {
    /**
     * Successfully fetched construction site.
     */
    200: {
        data: Construction;
    };
};

export type GetConstructionResponse = GetConstructionResponses[keyof GetConstructionResponses];

export type SupplyConstructionData = {
    body: {
        /**
         * The symbol of the ship supplying construction materials.
         */
        shipSymbol: string;
        /**
         * The symbol of the good to supply.
         */
        tradeSymbol: TradeSymbol;
        /**
         * Amount of units to supply.
         */
        units: number;
    };
    path: {
        /**
         * The system symbol
         */
        systemSymbol: string;
        /**
         * The waypoint symbol
         */
        waypointSymbol: string;
    };
    query?: never;
    url: '/systems/{systemSymbol}/waypoints/{waypointSymbol}/construction/supply';
};

export type SupplyConstructionResponses = {
    /**
     * Successfully supplied construction site.
     */
    201: {
        data: {
            construction: Construction;
            cargo: ShipCargo;
        };
    };
};

export type SupplyConstructionResponse = SupplyConstructionResponses[keyof SupplyConstructionResponses];

export type GetMarketData = {
    body?: never;
    path: {
        /**
         * The system symbol
         */
        systemSymbol: string;
        /**
         * The waypoint symbol
         */
        waypointSymbol: string;
    };
    query?: never;
    url: '/systems/{systemSymbol}/waypoints/{waypointSymbol}/market';
};

export type GetMarketResponses = {
    /**
     * Successfully fetched the market.
     */
    200: {
        data: Market;
    };
};

export type GetMarketResponse = GetMarketResponses[keyof GetMarketResponses];

export type GetJumpGateData = {
    body?: never;
    path: {
        /**
         * The system symbol
         */
        systemSymbol: string;
        /**
         * The waypoint symbol
         */
        waypointSymbol: string;
    };
    query?: never;
    url: '/systems/{systemSymbol}/waypoints/{waypointSymbol}/jump-gate';
};

export type GetJumpGateResponses = {
    /**
     * Jump gate details retrieved successfully.
     */
    200: {
        data: JumpGate;
    };
};

export type GetJumpGateResponse = GetJumpGateResponses[keyof GetJumpGateResponses];

export type GetShipyardData = {
    body?: never;
    path: {
        /**
         * The system symbol
         */
        systemSymbol: string;
        /**
         * The waypoint symbol
         */
        waypointSymbol: string;
    };
    query?: never;
    url: '/systems/{systemSymbol}/waypoints/{waypointSymbol}/shipyard';
};

export type GetShipyardResponses = {
    /**
     * Successfully fetched the shipyard.
     */
    200: {
        data: Shipyard;
    };
};

export type GetShipyardResponse = GetShipyardResponses[keyof GetShipyardResponses];

export type WebsocketDepartureEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/my/socket.io';
};

export type WebsocketDepartureEventsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetContractsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * What entry offset to request
         */
        page?: number;
        /**
         * How many entries to return per page
         */
        limit?: number;
    };
    url: '/my/contracts';
};

export type GetContractsResponses = {
    /**
     * Successfully listed contracts.
     */
    200: {
        data: Array<Contract>;
        meta: Meta;
    };
};

export type GetContractsResponse = GetContractsResponses[keyof GetContractsResponses];

export type GetContractData = {
    body?: never;
    path: {
        /**
         * The contract ID to accept.
         */
        contractId: string;
    };
    query?: never;
    url: '/my/contracts/{contractId}';
};

export type GetContractResponses = {
    /**
     * Successfully fetched contract.
     */
    200: {
        data: Contract;
    };
};

export type GetContractResponse = GetContractResponses[keyof GetContractResponses];

export type AcceptContractData = {
    body?: never;
    path: {
        /**
         * The contract ID to accept.
         */
        contractId: string;
    };
    query?: never;
    url: '/my/contracts/{contractId}/accept';
};

export type AcceptContractResponses = {
    /**
     * Successfully accepted contract.
     */
    200: {
        data: {
            contract: Contract;
            agent: Agent;
        };
    };
};

export type AcceptContractResponse = AcceptContractResponses[keyof AcceptContractResponses];

export type FulfillContractData = {
    body?: never;
    path: {
        /**
         * The ID of the contract to fulfill.
         */
        contractId: string;
    };
    query?: never;
    url: '/my/contracts/{contractId}/fulfill';
};

export type FulfillContractResponses = {
    /**
     * Successfully fulfilled a contract.
     */
    200: {
        data: {
            contract: Contract;
            agent: Agent;
        };
    };
};

export type FulfillContractResponse = FulfillContractResponses[keyof FulfillContractResponses];

export type DeliverContractData = {
    body: {
        /**
         * Symbol of a ship located in the destination to deliver a contract and that has a good to deliver in its cargo.
         */
        shipSymbol: string;
        /**
         * The symbol of the good to deliver.
         */
        tradeSymbol: string;
        /**
         * Amount of units to deliver.
         */
        units: number;
    };
    path: {
        /**
         * The ID of the contract.
         */
        contractId: string;
    };
    query?: never;
    url: '/my/contracts/{contractId}/deliver';
};

export type DeliverContractResponses = {
    /**
     * Successfully delivered cargo to contract.
     */
    200: {
        data: {
            contract: Contract;
            cargo: ShipCargo;
        };
    };
};

export type DeliverContractResponse = DeliverContractResponses[keyof DeliverContractResponses];

export type GetMyFactionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * What entry offset to request
         */
        page?: number;
        /**
         * How many entries to return per page
         */
        limit?: number;
    };
    url: '/my/factions';
};

export type GetMyFactionsResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<{
            symbol: string;
            reputation: number;
        }>;
        meta: Meta;
    };
};

export type GetMyFactionsResponse = GetMyFactionsResponses[keyof GetMyFactionsResponses];

export type GetMyAgentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/my/agent';
};

export type GetMyAgentResponses = {
    /**
     * Successfully fetched agent details.
     */
    200: {
        data: Agent;
    };
};

export type GetMyAgentResponse = GetMyAgentResponses[keyof GetMyAgentResponses];

export type GetMyAgentEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/my/agent/events';
};

export type GetMyAgentEventsResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<AgentEvent>;
    };
};

export type GetMyAgentEventsResponse = GetMyAgentEventsResponses[keyof GetMyAgentEventsResponses];

export type GetMyShipsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * What entry offset to request
         */
        page?: number;
        /**
         * How many entries to return per page
         */
        limit?: number;
    };
    url: '/my/ships';
};

export type GetMyShipsResponses = {
    /**
     * Successfully listed ships.
     */
    200: {
        data: Array<Ship>;
        meta: Meta;
    };
};

export type GetMyShipsResponse = GetMyShipsResponses[keyof GetMyShipsResponses];

export type PurchaseShipData = {
    body: {
        shipType: ShipType;
        /**
         * The symbol of the waypoint you want to purchase the ship at.
         */
        waypointSymbol: string;
    };
    path?: never;
    query?: never;
    url: '/my/ships';
};

export type PurchaseShipResponses = {
    /**
     * Purchased ship successfully.
     */
    201: {
        data: {
            ship: Ship;
            agent: Agent;
            transaction: ShipyardTransaction;
        };
    };
};

export type PurchaseShipResponse = PurchaseShipResponses[keyof PurchaseShipResponses];

export type GetMyAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/my/account';
};

export type GetMyAccountResponses = {
    /**
     * Default Response
     */
    200: {
        data: {
            account: {
                id: string;
                email: string | null;
                token?: string;
                createdAt: Date;
            };
        };
    };
};

export type GetMyAccountResponse = GetMyAccountResponses[keyof GetMyAccountResponses];

export type GetMyShipData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}';
};

export type GetMyShipResponses = {
    /**
     * Successfully fetched ship.
     */
    200: {
        data: Ship;
    };
};

export type GetMyShipResponse = GetMyShipResponses[keyof GetMyShipResponses];

export type CreateChartData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/chart';
};

export type CreateChartResponses = {
    /**
     * Successfully charted waypoint.
     */
    201: {
        data: {
            chart: Chart;
            waypoint: Waypoint;
            transaction: ChartTransaction;
            agent: Agent;
        };
    };
};

export type CreateChartResponse = CreateChartResponses[keyof CreateChartResponses];

export type NegotiateContractData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/negotiate/contract';
};

export type NegotiateContractResponses = {
    /**
     * Negotiate Contract 201 Response
     *
     * Successfully negotiated a new contract.
     */
    201: {
        data: {
            contract: Contract;
        };
    };
};

export type NegotiateContractResponse = NegotiateContractResponses[keyof NegotiateContractResponses];

export type GetShipCooldownData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/cooldown';
};

export type GetShipCooldownResponses = {
    /**
     * Successfully fetched ship's cooldown.
     */
    200: {
        data: Cooldown;
    };
    /**
     * No cooldown.
     */
    204: unknown;
};

export type GetShipCooldownResponse = GetShipCooldownResponses[keyof GetShipCooldownResponses];

export type DockShipData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/dock';
};

export type DockShipResponses = {
    /**
     * Dock Ship 200 Response
     *
     * The ship has successfully docked at its current location.
     */
    200: {
        data: {
            nav: ShipNav;
        };
    };
};

export type DockShipResponse = DockShipResponses[keyof DockShipResponses];

export type ExtractResourcesData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/extract';
};

export type ExtractResourcesResponses = {
    /**
     * Successfully extracted resources.
     */
    201: {
        data: {
            extraction: Extraction;
            cooldown: Cooldown;
            cargo: ShipCargo;
            modifiers?: Array<WaypointModifier>;
            events: Array<ShipConditionEvent>;
        };
    };
};

export type ExtractResourcesResponse = ExtractResourcesResponses[keyof ExtractResourcesResponses];

export type ExtractResourcesWithSurveyData = {
    body?: Survey;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/extract/survey';
};

export type ExtractResourcesWithSurveyResponses = {
    /**
     * Successfully extracted resources.
     */
    201: {
        data: {
            extraction: Extraction;
            cooldown: Cooldown;
            cargo: ShipCargo;
            modifiers?: Array<WaypointModifier>;
            events: Array<ShipConditionEvent>;
        };
    };
};

export type ExtractResourcesWithSurveyResponse = ExtractResourcesWithSurveyResponses[keyof ExtractResourcesWithSurveyResponses];

export type JettisonData = {
    body: {
        symbol: TradeSymbol;
        /**
         * Amount of units to jettison of this good.
         */
        units: number;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/jettison';
};

export type JettisonResponses = {
    /**
     * Jettison successful.
     */
    200: {
        data: {
            cargo: ShipCargo;
        };
    };
};

export type JettisonResponse = JettisonResponses[keyof JettisonResponses];

export type JumpShipData = {
    body: {
        /**
         * The symbol of the waypoint to jump to. The destination must be a connected waypoint.
         */
        waypointSymbol: string;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/jump';
};

export type JumpShipResponses = {
    /**
     * Jump successful.
     */
    200: {
        data: {
            nav: ShipNav;
            cooldown: Cooldown;
            transaction: MarketTransaction;
            agent: Agent;
        };
    };
};

export type JumpShipResponse = JumpShipResponses[keyof JumpShipResponses];

export type CreateShipSystemScanData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/scan/systems';
};

export type CreateShipSystemScanResponses = {
    /**
     * Successfully scanned for nearby systems.
     */
    201: {
        data: {
            cooldown: Cooldown;
            /**
             * List of scanned systems.
             */
            systems: Array<ScannedSystem>;
        };
    };
};

export type CreateShipSystemScanResponse = CreateShipSystemScanResponses[keyof CreateShipSystemScanResponses];

export type CreateShipWaypointScanData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/scan/waypoints';
};

export type CreateShipWaypointScanResponses = {
    /**
     * Successfully scanned for nearby waypoints.
     */
    201: {
        data: {
            cooldown: Cooldown;
            /**
             * List of scanned waypoints.
             */
            waypoints: Array<ScannedWaypoint>;
        };
    };
};

export type CreateShipWaypointScanResponse = CreateShipWaypointScanResponses[keyof CreateShipWaypointScanResponses];

export type CreateShipShipScanData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/scan/ships';
};

export type CreateShipShipScanResponses = {
    /**
     * Successfully scanned for nearby ships.
     */
    201: {
        data: {
            cooldown: Cooldown;
            /**
             * List of scanned ships.
             */
            ships: Array<ScannedShip>;
        };
    };
};

export type CreateShipShipScanResponse = CreateShipShipScanResponses[keyof CreateShipShipScanResponses];

export type GetScrapShipData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/scrap';
};

export type GetScrapShipResponses = {
    /**
     * Successfully retrieved the amount of value that will be returned when scrapping a ship.
     */
    200: {
        data: {
            transaction: ScrapTransaction;
        };
    };
};

export type GetScrapShipResponse = GetScrapShipResponses[keyof GetScrapShipResponses];

export type ScrapShipData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/scrap';
};

export type ScrapShipResponses = {
    /**
     * Ship scrapped successfully.
     */
    200: {
        data: {
            agent: Agent;
            transaction: ScrapTransaction;
        };
    };
};

export type ScrapShipResponse = ScrapShipResponses[keyof ScrapShipResponses];

export type NavigateShipData = {
    body: {
        /**
         * The symbol of the waypoint to navigate/warp to.
         */
        waypointSymbol: string;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/navigate';
};

export type NavigateShipResponses = {
    /**
     * The successful transit information including the route details and changes to ship fuel. The route includes the expected time of arrival.
     */
    200: {
        data: {
            nav: ShipNav;
            fuel: ShipFuel;
            events: Array<ShipConditionEvent>;
        };
    };
};

export type NavigateShipResponse = NavigateShipResponses[keyof NavigateShipResponses];

export type WarpShipData = {
    body: {
        /**
         * The symbol of the waypoint to navigate/warp to.
         */
        waypointSymbol: string;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/warp';
};

export type WarpShipResponses = {
    /**
     * The successful transit information including the route details and changes to ship fuel. The route includes the expected time of arrival.
     */
    200: {
        data: {
            nav: ShipNav;
            fuel: ShipFuel;
            events: Array<ShipConditionEvent>;
        };
    };
};

export type WarpShipResponse = WarpShipResponses[keyof WarpShipResponses];

export type OrbitShipData = {
    body?: never;
    path: {
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/orbit';
};

export type OrbitShipResponses = {
    /**
     * Orbit Ship 200 Response
     *
     * The ship has successfully moved into orbit at its current location.
     */
    200: {
        data: {
            nav: ShipNav;
        };
    };
};

export type OrbitShipResponse = OrbitShipResponses[keyof OrbitShipResponses];

export type PurchaseCargoData = {
    /**
     * Purchase Cargo Request
     */
    body: {
        symbol: TradeSymbol;
        /**
         * The number of units of the good to purchase.
         */
        units: number;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/purchase';
};

export type PurchaseCargoResponses = {
    /**
     * Purchase Cargo 201 Response
     *
     * Purchased goods successfully.
     */
    201: {
        data: {
            cargo: ShipCargo;
            transaction: MarketTransaction;
            agent: Agent;
        };
    };
};

export type PurchaseCargoResponse = PurchaseCargoResponses[keyof PurchaseCargoResponses];

export type ShipRefineData = {
    body: {
        /**
         * The type of good to produce out of the refining process.
         */
        produce: 'IRON' | 'COPPER' | 'SILVER' | 'GOLD' | 'ALUMINUM' | 'PLATINUM' | 'URANITE' | 'MERITIUM' | 'FUEL';
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/refine';
};

export type ShipRefineResponses = {
    /**
     * Ship Refine 201 Response
     *
     * The ship has successfully refined goods.
     */
    201: {
        data: {
            cargo: ShipCargo;
            cooldown: Cooldown;
            /**
             * Goods that were produced by this refining process.
             */
            produced: Array<{
                /**
                 * Symbol of the good.
                 */
                tradeSymbol: TradeSymbol;
                /**
                 * Amount of units of the good.
                 */
                units: number;
            }>;
            /**
             * Goods that were consumed during this refining process.
             */
            consumed: Array<{
                /**
                 * Symbol of the good.
                 */
                tradeSymbol: TradeSymbol;
                /**
                 * Amount of units of the good.
                 */
                units: number;
            }>;
        };
    };
};

export type ShipRefineResponse = ShipRefineResponses[keyof ShipRefineResponses];

export type RefuelShipData = {
    body?: {
        /**
         * The amount of fuel to fill in the ship's tanks. When not specified, the ship will be refueled to its maximum fuel capacity. If the amount specified is greater than the ship's remaining capacity, the ship will only be refueled to its maximum fuel capacity. The amount specified is not in market units but in ship fuel units.
         */
        units?: number;
        /**
         * Wether to use the FUEL thats in your cargo or not.
         */
        fromCargo?: boolean | unknown;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/refuel';
};

export type RefuelShipResponses = {
    /**
     * Refueled successfully.
     */
    200: {
        data: {
            agent: Agent;
            fuel: ShipFuel;
            cargo?: ShipCargo;
            transaction: MarketTransaction;
        };
    };
};

export type RefuelShipResponse = RefuelShipResponses[keyof RefuelShipResponses];

export type GetRepairShipData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/repair';
};

export type GetRepairShipResponses = {
    /**
     * Successfully retrieved the cost of repairing a ship.
     */
    200: {
        data: {
            transaction: RepairTransaction;
        };
    };
};

export type GetRepairShipResponse = GetRepairShipResponses[keyof GetRepairShipResponses];

export type RepairShipData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/repair';
};

export type RepairShipResponses = {
    /**
     * Ship repaired successfully.
     */
    200: {
        data: {
            agent: Agent;
            ship: Ship;
            transaction: RepairTransaction;
        };
    };
};

export type RepairShipResponse = RepairShipResponses[keyof RepairShipResponses];

export type SellCargoData = {
    /**
     * SellCargoRequest
     */
    body: {
        symbol: TradeSymbol;
        /**
         * Amounts of units to sell of the selected good.
         */
        units: number;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/sell';
};

export type SellCargoResponses = {
    /**
     * Sell Cargo 201 Response
     *
     * Cargo was successfully sold.
     */
    201: {
        data: {
            cargo: ShipCargo;
            transaction: MarketTransaction;
            agent: Agent;
        };
    };
};

export type SellCargoResponse = SellCargoResponses[keyof SellCargoResponses];

export type SiphonResourcesData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/siphon';
};

export type SiphonResourcesResponses = {
    /**
     * Siphon successful.
     */
    201: {
        data: {
            siphon: Siphon;
            cooldown: Cooldown;
            cargo: ShipCargo;
            events: Array<ShipConditionEvent>;
        };
    };
};

export type SiphonResourcesResponse = SiphonResourcesResponses[keyof SiphonResourcesResponses];

export type CreateSurveyData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/survey';
};

export type CreateSurveyResponses = {
    /**
     * Surveys has been created.
     */
    201: {
        data: {
            cooldown: Cooldown;
            /**
             * Surveys created by this action.
             */
            surveys: Array<Survey>;
        };
    };
};

export type CreateSurveyResponse = CreateSurveyResponses[keyof CreateSurveyResponses];

export type TransferCargoData = {
    /**
     * Transfer Cargo Request
     */
    body: {
        tradeSymbol: TradeSymbol;
        /**
         * Amount of units to transfer.
         */
        units: number;
        /**
         * The symbol of the ship to transfer to.
         */
        shipSymbol: string;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/transfer';
};

export type TransferCargoResponses = {
    /**
     * Transfer Cargo 200 Response
     *
     * Cargo transferred successfully.
     */
    200: {
        data: {
            cargo: ShipCargo;
            targetCargo: ShipCargo;
        };
    };
};

export type TransferCargoResponse = TransferCargoResponses[keyof TransferCargoResponses];

export type GetMyShipCargoData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/cargo';
};

export type GetMyShipCargoResponses = {
    /**
     * Successfully fetched ship's cargo.
     */
    200: {
        data: ShipCargo;
    };
};

export type GetMyShipCargoResponse = GetMyShipCargoResponses[keyof GetMyShipCargoResponses];

export type GetShipModulesData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/modules';
};

export type GetShipModulesResponses = {
    /**
     * Successfully retrieved ship modules.
     */
    200: {
        data: Array<ShipModule>;
    };
};

export type GetShipModulesResponse = GetShipModulesResponses[keyof GetShipModulesResponses];

export type InstallShipModuleData = {
    body: {
        /**
         * The symbol of the module to install.
         */
        symbol: string;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/modules/install';
};

export type InstallShipModuleResponses = {
    /**
     * Successfully installed the module on the ship.
     */
    201: {
        data: {
            agent: Agent;
            modules: Array<ShipModule>;
            cargo: ShipCargo;
            transaction: ShipModificationTransaction;
        };
    };
};

export type InstallShipModuleResponse = InstallShipModuleResponses[keyof InstallShipModuleResponses];

export type RemoveShipModuleData = {
    body: {
        /**
         * The symbol of the module to remove.
         */
        symbol: string;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/modules/remove';
};

export type RemoveShipModuleResponses = {
    /**
     * Successfully removed the module from the ship.
     */
    201: {
        data: {
            agent: Agent;
            modules: Array<ShipModule>;
            cargo: ShipCargo;
            transaction: ShipModificationTransaction;
        };
    };
};

export type RemoveShipModuleResponse = RemoveShipModuleResponses[keyof RemoveShipModuleResponses];

export type GetMountsData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/mounts';
};

export type GetMountsResponses = {
    /**
     * Get Mounts 200 Response
     *
     * Successfully retrieved ship mounts.
     */
    200: {
        data: Array<ShipMount>;
    };
};

export type GetMountsResponse = GetMountsResponses[keyof GetMountsResponses];

export type InstallMountData = {
    /**
     * Install Mount Request
     */
    body: {
        /**
         * The symbol of the mount to install.
         */
        symbol: string;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/mounts/install';
};

export type InstallMountResponses = {
    /**
     * Install Mount 201 Response
     *
     * Successfully installed the mount.
     */
    201: {
        data: {
            agent: Agent;
            /**
             * List of installed mounts after the installation of the new mount.
             */
            mounts: Array<ShipMount>;
            cargo: ShipCargo;
            transaction: ShipModificationTransaction;
        };
    };
};

export type InstallMountResponse = InstallMountResponses[keyof InstallMountResponses];

export type RemoveMountData = {
    /**
     * Remove Mount Request
     */
    body: {
        /**
         * The symbol of the mount to remove.
         */
        symbol: string;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/mounts/remove';
};

export type RemoveMountResponses = {
    /**
     * Remove Mount 201 Response
     *
     * Successfully removed the mount.
     */
    201: {
        data: {
            agent: Agent;
            /**
             * List of installed mounts after the removal of the selected mount.
             */
            mounts: Array<ShipMount>;
            cargo: ShipCargo;
            transaction: ShipModificationTransaction;
        };
    };
};

export type RemoveMountResponse = RemoveMountResponses[keyof RemoveMountResponses];

export type GetShipNavData = {
    body?: never;
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/nav';
};

export type GetShipNavResponses = {
    /**
     * The current nav status of the ship.
     */
    200: {
        data: ShipNav;
    };
};

export type GetShipNavResponse = GetShipNavResponses[keyof GetShipNavResponses];

export type PatchShipNavData = {
    body?: {
        flightMode?: ShipNavFlightMode;
    };
    path: {
        /**
         * The symbol of the ship.
         */
        shipSymbol: string;
    };
    query?: never;
    url: '/my/ships/{shipSymbol}/nav';
};

export type PatchShipNavResponses = {
    /**
     * Success response for updating the nav configuration of a ship.
     */
    200: {
        data: {
            nav: ShipNav;
            fuel: ShipFuel;
            events: Array<ShipConditionEvent>;
        };
    };
};

export type PatchShipNavResponse = PatchShipNavResponses[keyof PatchShipNavResponses];

export type RegisterData = {
    body: {
        /**
         * Your desired agent symbol. This will be a unique name used to represent your agent, and will be the prefix for your ships.
         */
        symbol: string;
        faction: FactionSymbol;
    };
    path?: never;
    query?: never;
    url: '/register';
};

export type RegisterResponses = {
    /**
     * Successfully registered.
     */
    201: {
        data: {
            /**
             * A Bearer token for accessing secured API endpoints.
             */
            token: string;
            agent: Agent;
            faction: Faction;
            contract: Contract;
            ships: Array<Ship>;
        };
    };
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];
